### ISSUE TITLE
How to pass updateSelectBounds to parent component?

### ISSUE THREAD

**Issue by neolite** [sanusart/react-dropdown-select#100]
Hi!
I need to resize the dropdown dynamically, how a can make this?

**Comment by sanusart** [comment]
Can you please be more specific?

**Comment by neolite** [comment]
[Video](https://imgur.com/a/Q6kSJtN)

 When i resizing a parent element, select not resizing when is opened

**Comment by sanusart** [comment]
@neolite I see, thanks for clarification.

`state.selectBounds` should provide you with the current size
https://sanusart.github.io/react-dropdown-select/prop/dropdown-renderer

![image](https://user-images.githubusercontent.com/267718/82921336-f1d32b80-9f80-11ea-959c-b8687c181e6f.png)
