### ISSUE TITLE
searchFn callback fires twice when typing in search bar

### ISSUE THREAD

**Issue by MustafaFaris** [sanusart/react-dropdown-select#101]
Hi there, I'm having a problem with the `searchFn` callback, apparently each time you type in the search bar the `searchFn` callback gets fired twice. The same thing doesn't seem to happen with `handleKeyDownFn` callback, however the state it returns is a bit late so I can't use it. 

I've created this sandbox [here](https://codesandbox.io/s/searchfn-callback-issue-bfr3u) to demonstrate the issue, try typing in the search bar and then check the console.

**Comment by AnDyro751** [comment]
Any solution?

**Comment by akuji1993** [comment]
If you're looking for an easy solution to wrap this for now, you could either debounce, or just do this: 

`  const onSearch = e => {
    if (searchValue !== e.state.search) {
      setSearchValue(e.state.search);
    }
  };`

That way you have pretty much the same solution that a componentDidUpdate with an equality check would give you.

**Comment by sanusart** [comment]
I am extremely out of time recently, so if someone can submit a patch for this it could be great. If not it would have to wait a bit. Apologies if inconvenient.

**Comment by sanusart** [comment]
reverted for now
