### ISSUE TITLE
setSearch method issue

### ISSUE THREAD

**Issue by lomm28** [sanusart/react-dropdown-select#103]
Hi everyone,
I wanted to inquire about using setSearch method to preserve search text in `Input`. I've created [sandbox](https://codesandbox.io/s/search-value-issue-6q4jz) to demonstrate what I'm trying to achieve.
Basically, I'm overwriting default **handleKeyDownFn** method where I set multiple values based on user's input upon Enter click, but I want to keep the user's input text instead of first matching value that is currently shown in the input field. I'm trying to use **setSearch** to preserve input but it doesn't seem to work.
Any ideas on how it can be achieved? Thanks!

**Comment by sanusart** [comment]
Is overriding Input is an option? Then you'll have full control over it.
Signature:
`inputRenderer({ props, state, methods, inputRef: this.input })`

**Comment by lomm28** [comment]
Hi! Thank you! I will try it out.

**Comment by Nogias9x** [comment]
Hi @sanusart ,

I'm facing the same problem. I realized whenever `contentRenderer` is overwritten, search function doesn't work anymore @sanusart . Do you have any idea how to fix it?

**Comment by sanusart** [comment]
@Nogias9x as the [docs](https://sanusart.github.io/react-dropdown-select/api) state:  "by using renderer props to override components some of the functionality will have to be handled manually with a help of internal props, states and methods exposed".

You can check this example to see an idea of how some functionality can be brought back/reconstructed by using exposed props and methods.
https://sanusart.github.io/react-dropdown-select/examples#Custom-Content-And-Dropdown-renderers
