### ISSUE TITLE
how to use style property?

### ISSUE THREAD

**Issue by bkyam** [sanusart/react-dropdown-select#106]
This library looks great, and lean.

I'd like to be able to have the component have multiple styles/themes. AKA Light theme or Dark theme.

Is that what the 'style' property is for, and if so, are there any examples of how that would work? I didn't see any in your examples (or just missed it).

I see this example for how to customize the style, but its a single 'theme':

https://github.com/sanusart/react-dropdown-select/blob/master/docs/src/examples/Styled.js

**Comment by sanusart** [comment]
Hey you can style it as any other component with css. It does not provide themes. The styled in the example is just css in js emotion. 
If you need to have themes I'd suggest creating 2 kinds of css and change the className of the component to toggle dark/light styling.
