### ISSUE TITLE
Not able to change font style, fontsize and color of placeholder 

### ISSUE THREAD

**Issue by bipindubey-technoark** [sanusart/react-dropdown-select#107]
I am not able to change the font style, fontsize and color of placeholder in react-dropdown-select..
I have tried using jss but it is not working............ not able to change color of placeholder and size of it
Please help.......
Thank you

**Comment by sanusart** [comment]
It is a real placeholder. Have you tried to target it with :placeholder pseudo selector?

**Comment by bipindubey-technoark** [comment]
Yess, @sanusart  i have tried that but nothing is working for me

**Comment by sanusart** [comment]
https://codesandbox.io/s/style-3jf4l?file=/src/demo-styles.css:148-226

**Comment by bipindubey-technoark** [comment]
Thanks @sanusart this works for me

**Comment by bipindubey-technoark** [comment]
I am not able to apply outline:none css.
its not working for me
onclick of dropdown it shows grey dark border and light blue color border i have to disable that
