### ISSUE TITLE
Dropdown size and position not calculated

### ISSUE THREAD

**Issue by gittysam** [sanusart/react-dropdown-select#108]
Hi !

The dropdown size and position cannot be calculated right (width is 0 ; only the shadow makes the element visible).
There's no problem with the Select props including 'options'.

When the browser window is resized afterwards, calculations are the made right and the dropdown appears at the right position and has the right size.

So it seems the size and position of the dropdown component could not be computed when the Select component is mounted.
I thought maybe these values could not be calculated before the parent component of the Select component was itself mounted.
So I tried forceUpdate() on the Select component, inside the parent componentDidMount method : not working.

I also tried to update the 'dropdownHeight' prop after the parent component is mounted (in componentDidMount method), but it's not working any better.

Do you have any idea ?

Thanks !
Samuel

**Comment by sanusart** [comment]
I do not understand the issue, can you reproduce in codesandbox?
