### ISSUE TITLE
Ui issue while using disabled prop

### ISSUE THREAD

**Issue by bipindubey-technoark** [sanusart/react-dropdown-select#109]
When use disabled prop then background color and all changes to light color but i want to just disabled onclick and i dont want to open dropdown and hide the cross icon cancel from list
any solution which disabled select dropdown without changing the color of select tag

**Comment by sanusart** [comment]
https://codesandbox.io/s/style-4d2w2?file=/src/demo-styles.css:148-188

**Comment by bipindubey-technoark** [comment]
Thanks again @sanusart . it works fine and thanks for quick reply
