### ISSUE TITLE
createNew allows creation of duplicate items because it doesn't check against the existing options...

### ISSUE THREAD

**Issue by DLatheron** [sanusart/react-dropdown-select#116]
When the component attempts to create a new item (line 44 of `Dropdown.js`) it makes a call to `valueExistIngInSelected` which checks to see if the value already exists in the `values` property of the internal `state`. 

Whilst this prevents you from having the same item selected twice in the drop down, because it doesn't check the `props.options` list it does not stop you from creating multiple options (there is no way for the component user to protect against this creation as there is no way to feedback from the `createNew` callback that the new item should not be created.

You can repo this very easily in your create new examples because it will give you the option to create a new instance of a person from the existing data.

**Comment by sanusart** [comment]
Available since v4.5.1
Thanks @DLatheron for proper review and input, on vacation so my brain is not in the code

**Comment by DLatheron** [comment]
Thanks, sorry to interrupt your holiday... I’m back in work on Thursday so will pull your new release then.

Cheers

Dave

**Comment by sanusart** [comment]
All good, my fauld I am checking mail, there are no real holidays anymore with covid :)
