### ISSUE TITLE
Editable/Custom content renderer to edit selected value and filter dropdown

### ISSUE THREAD

**Issue by sudheer-ranga** [sanusart/react-dropdown-select#123]
Thanks for the plugin. Really appreciate the efforts.

I want to be able to edit the selected value and show the filtered values in the dropdown, just like how autocomplete would work.

[Something like this](https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_autocomplete)

Once you select a value from the dropdown, you should be able to click on the text box and edit the text which shows the filtered results. With the current implementation, both the text input and the value is shown.

**Comment by sanusart** [comment]
Hey, this is not intended to be autocomplete, but closer to mimic a select. 
However it is pretty flexible and there are enough functionality exposed to create a "custom content" renderer as in this example https://sanusart.github.io/react-dropdown-select/examples/#Custom-Content-And-Dropdown-renderers

Basically you can override whatever is shown as the selects content. But from your example it seems like you'd be better of with any autoselect lib out there as there is some work for you to put to make it proper auto-select as in the example.
