### ISSUE TITLE
Integrate checkbox with text in dropdown options

### ISSUE THREAD

**Issue by bipindubey-technoark** [sanusart/react-dropdown-select#124]
I have to add checkbox before the option text 
Thanks

**Comment by sanusart** [comment]
https://sanusart.github.io/react-dropdown-select/prop/option-renderer

**Comment by bipindubey-technoark** [comment]
Thanks @sanusart

**Comment by bipindubey-technoark** [comment]
@sanusart the sandbox link given by you is different from my use case. in your sandbox after select it shows styled custom data in dropdown values... i want to add checkbox with label in options not in values
EG. Country drodpown will have suppose 3 country
so option will be like
checkbox India
checkbox USA
checkbox Brazil something like this

**Comment by bipindubey-technoark** [comment]
I have to used itemRenderer for it I got it
Thanks @sanusart  for your help
