### ISSUE TITLE
Dynamic options

### ISSUE THREAD

**Issue by RoloAria** [sanusart/react-dropdown-select#125]
Hi I really like this package. But I was wondering if there is a way to modify the options dynamically.

I'm passing the options props dynamically , the props changed correctly, but the dropdown doesn't update until I close it and open it again.

`import React, { useState, useEffect } from 'react';
import Select from 'react-dropdown-select'

const Search = (props) => {
    const [options, setOptions] = useState()
    const [searchValue, setSearchValue] = useState(null);

    useEffect(() => {
        setOptions(props.options)
    }, [])

    const onSearch = e => {
        const newValue = e.state.search
        if (searchValue !== newValue) {
            setSearchValue(newValue)
            if (props.onChangeSearchValue && newValue) {
                //when the search value changes, I receive new options
                const newOptions = props.onChangeSearchValue()
                setOptions(newOptions)
            }
        }
    };

    return <Select
        searchable
        clearable
        options={options}
        searchFn={onSearch}
        valueField={props.valueField}
        labelField={props.labelField} />

}
export default Search;`

Is there a way to achive this?

**Comment by sanusart** [comment]
Hey, this one load it from external resource - so I would imagine it should not have an issue to load if they change.

https://codesandbox.io/s/epic-herschel-194rp?file=/src/App.js

**Comment by RoloAria** [comment]
Thank you so much!
