### ISSUE TITLE
handleKeyDownFn one character behind typed string (n-1)

### ISSUE THREAD

**Issue by matccent** [sanusart/react-dropdown-select#126]
I have very simple component:

```
<Select handleKeyDownFn={e => console.log(e.state.search)} />
```

When I type a string, `console.log` is one character behind the content of the input. For example:

Input value visible on screen | console.log output
------------ | -------------
a | <empty string>
ab | a
abc | ab
abcd | abc

Is it expected behaviour? How do I get exact value from the input?

**Comment by sanusart** [comment]
By using this you are overriding function that is triggered on keyDown even https://github.com/sanusart/react-dropdown-select/blob/master/src/index.js#L492

AFAIK, text fields behave differently on keyDown and keyPress so expecting text changes from it immediately is not correct as text being typed in text field.

if you log the key you'll see it firing instantly:

`<Select handleKeyDownFn={e => console.log(e.event.key)} />`

What is your use case for this?

**Comment by matccent** [comment]
I have thousands of options, so I made it dynamic. When you type in my input, it loads suggestions from the backend using phrase. Unfortunately it's always one character behind value actually typed.

**Comment by sanusart** [comment]
I see. Unfortunately my previous comment still stands, text inputs react differently on keyDown.

If you dont mind to pull all of the options into the state you can use windowed dropdown with proper performance like this example, https://sanusart.github.io/react-dropdown-select/examples#Windowed-(20000-items)

Or we can maybe add new prop for keyPress which will likely solve the input event.

If you have any suggestions, don't hesitate.
