### ISSUE TITLE
Dropdown cut off

### ISSUE THREAD

**Issue by svermaak** [sanusart/react-dropdown-select#128]
Here is react-dropdown-select vs dropdown. For some reason, react-dropdown-select is cut off

react-dropdown-select
![image](https://user-images.githubusercontent.com/12259728/94512890-9bdd0000-0260-11eb-93e5-4af8362eae2d.png)

Dropdown
![image](https://user-images.githubusercontent.com/12259728/94512907-a5666800-0260-11eb-97a7-afed0fd0d71f.png)

**Comment by sanusart** [comment]
I guess your parent container overvlown
https://github.com/sanusart/react-dropdown-select/issues/112

**Comment by svermaak** [comment]
Like this? When I do it stops working (no items)
```
React.createElement(Select, {
key: itemId,
values: value,
 labelField: "text",
valueField: "key",
multi: true,
searchBy: "text",
portal: typeof document !== undefined && document.body,
onChange: (event) => {},
options: []
}
```

**Comment by sanusart** [comment]
Hard to say from this snippet as your options are `[]`. Can you reproduce somewhere?
It works on the demo too https://sanusart.github.io/react-dropdown-select/examples/#Render-dropdown-in-body
