### ISSUE TITLE
Icons with text in dropdown messing up pillows and other styling

### ISSUE THREAD

**Issue by theabhinavdas** [sanusart/react-dropdown-select#129]
I've been able to use itemRenderer and contentRenderer to get icons with text in my dropdown, and maintain that with the rendering. However, the pillows and other aspects of the original style of your component are overridden. Is there a way to get them back? Also, can I pass component props to the renderer? For example, I want to make keepSelectedInList false, but doing that to the <Select> doesn't propagate changes, probably due to using itemRenderer.

Example code: [https://paste.ee/p/smLz4](https://paste.ee/p/smLz4) -- sorry, github issues was malformatting my markdown for some odd reason.

**Comment by sanusart** [comment]
Hey, when overriding components (https://sanusart.github.io/react-dropdown-select/api) - you will have to handle other functionality by yourself. Meaning you will have to implement your own `keepSelectedInList`

**Comment by theabhinavdas** [comment]
I see.. Is there a way to achieve icons with my list without having to override the component?

**Comment by sanusart** [comment]
Sure,

You can easily support `keepSelectedInList`, just add this to the top of your `audienceItemRenderer()` (add `props` parameter)
```
if (!props.keepSelectedInList && methods.isSelected(item)) {
      return null;
}
```

**Comment by theabhinavdas** [comment]
Wow, super elegant. The suggested answer works as expected.

Sorry to extend this question, but can I also get the other visual aspects like the pillows with the cross mark etc?

Also, is this the right way to use your component for my use-case?

**Comment by sanusart** [comment]
Cool, yes this is totally correct use, this component exposes some minimal setup for day-to-day use and allows to override if anything more complicated/different needed.

You can use `optionRenderer()` for pillows like this example bellow. You will have to handle overridden component parts manually, but this should be pretty strait forward using exposed functions and properties.

https://sanusart.github.io/react-dropdown-select/prop/option-renderer

**Comment by theabhinavdas** [comment]
Awesome, thanks for clarifying. You the best! 😄 💯

**Comment by theabhinavdas** [comment]
Hey, sorry, didn't want to open a new ticket. So reopening this one.

I used optionRenderer to make it work as expected (pillows, and other styling) for multi select dropdowns. But the styling doesn't work for non-multi-select dropdowns. Is that intended behaviour? 

I was wondering if consistent styling can be applied with optionRenderer irrelevant of multi being true or false? If so, how may I achieve that?

TIA!
