### ISSUE TITLE
`values` props are not working with `multi` option

### ISSUE THREAD

**Issue by jayasurian123** [sanusart/react-dropdown-select#13]
I was trying to set the `values` prop externally to the `Select` dropdown. It would work perfectly when the reference of the `values` props are same. But if we are using `redux` or any other external state management it will not work.

I created a small reproducible scenario here. 
https://codesandbox.io/s/external-clear-68i29 

I have also had a look at the code and the issue which i suspect is 
https://github.com/sanusart/react-dropdown-select/blob/4441b36d8c734813582d920c5bcab7a31dd9accd/src/index.js#L107

We may need to have a proper array comparison here.
eg:
```javaScript
 JSON.stringify(prevProps.values) ===  JSON.stringify(prevState.values)
```

Let me know if you need any more info from my side!

thanks for the nice lib.

**Comment by sanusart** [comment]
Hey @jayasurian123 please checkout slightly modified fork of your sandbox (note the line 58-59 for correction) 
https://codesandbox.io/s/external-clear-w0ukz Does this addresses the issue?

**Comment by jayasurian123** [comment]
hi @sanusart I know that would work 😇. 

The example was just a simplification of showing external state management like redux state would not work with the current implementation. Thats why cloned the `value` state.

I have come across this because of this scenario.
Selecting Dropdown options shows the widgets / modules in the page. And once widget/ modules are closed the dropdown should reflex the changes. So need to have an external state management to store the state. 

It would be always better to compare the array instead of their reference. Or removing `prevProps.values === prevState.values` (not sure that would break some other feature).

**Comment by sanusart** [comment]
@jayasurian123 got it. 
Will check this out with cloned. That comparation needed for proper internal and external change detection. I guess you right and real equality comparation needed. 
Thanks for clarifying this.

**Comment by jayasurian123** [comment]
@sanusart 👍

**Comment by sanusart** [comment]
@jayasurian123 Seems like scenario you posted works with 3.1.0. Thanks for taking time to report and investigate!

**Comment by jayasurian123** [comment]
@sanusart Thanks a ton. It's a fantastic lib. Keep up the great work 👍
