### ISSUE TITLE
Custom dropdown is not rendered properly.

### ISSUE THREAD

**Issue by zeel91297** [sanusart/react-dropdown-select#130]
Dropdown is not rendered completely when it is opened for the first time after the page is rendered.
![Screen Shot 2020-10-08 at 4 13 12 PM](https://user-images.githubusercontent.com/28985505/95448558-2b7d5f80-0981-11eb-9860-48a3ced784fb.png)

This is how dropdown is shown when it is first time clicked to open. After that if I start typing something it will behave normally.

I'm sharing here a snippet of my code.
I've also checked that whether data is getting bind to **certificates** before I click to open dropdown.

`<StyledSelect
                  name="certificates"
                  className="rounded state-dropdown shadow-none"
                  multi
                  placeholder="Start Typing Initials"
                  options={certificates}
                  values={selectedCertificates}
                  onChange={(value) => {
                    setselectedCertificates(value);
                  }}
                  valueField="id"
                  labelField="name"
                  searchable
                  searchBy="name"
                  sortBy="name"
                  itemRenderer={({ item, itemIndex, methods }) => (
                    <StyledItem>
                      <div>
                        <Form.Check
                          className="custom-check shadow-none pl-5 py-2"
                          custom
                          type="checkbox"
                          value={item.id}
                          id={itemIndex + 1}
                          onChange={() => {
                            methods.addItem(item);
                          }}
                          label={item.name}
                          checked={methods.isSelected(item)}
                        />
                      </div>
                    </StyledItem>
                  )}
                  clearable
                />`

**Comment by sanusart** [comment]
Hey, it's hard to say just from this snippet. Can you please reproduce in codesandbox?

**Comment by zeel91297** [comment]
I tried generating same thing in the sandbox but not working.
https://codesandbox.io/s/agitated-swanson-zed1u?file=/src/App.js

**Comment by sanusart** [comment]
You mean it is working in codesandbox, right?

**Comment by zeel91297** [comment]
Yes, but actually it's not working in my project.

**Comment by sanusart** [comment]
Maybe try to disable stuff and enable them gradually. This is usually works for me when there is nothing to debug

**Comment by zeel91297** [comment]
@sanusart The above issue is resolved by adding below css class:

`.css-93ilmd-DropDown{
    width:100%;
    margin-top:48px;
  }`

**Comment by mwlpeeters** [comment]
I'm running into the same problem.

I had to add the following css:

.css-93ilmd-DropDown {
    width: 100% !important;
    margin-top: 36px;
}

**Comment by devpms** [comment]
running into same issue. its difficult to give a version that can be reproduced on sandbox.

**Comment by sanusart** [comment]
It is not a version thing. I'd say it is something related to the css reset, or maybe parent witdth/display css settings.

**Comment by adarshsuresh12** [comment]
Same thing occured twice, but not able to reproduce it. Tried every conditions
