### ISSUE TITLE
Component not re-rendered

### ISSUE THREAD

**Issue by Lebron1992** [sanusart/react-dropdown-select#132]
Assume we have the objects to display:
```
[
{ id: '1', value: '1' },
{ id: '2', value: '2' },
{ id: '3', value: '3' },
{ id: '4', value: '4' },
{ id: '5', value: '5' },
{ id: '6', value: '6' }
]
```
The reproduce steps (The value object omitted):
1. set dropdown `values` to ` ["1"]` programmatically
2. manually select more values to` ["1", "2", "3", "4", "5", "6"] ` 
3. set dropdown `values` to ` ["2"] ` programmatically, the comoponent not re-rendered, all six values still being selected.

if the bug has not occurred after the above steps, please repeat step 1 to set `values` to `["2"], ["3"], ["2", "3"], ["4"]` ..., one by one, and contiune following steps.

**Comment by sanusart** [comment]
Cannot reproduce:
https://codesandbox.io/s/open-on-top-forked-0llec?file=/src/index.tsx

**Comment by Lebron1992** [comment]
@sanusart  Thanks for your reply. Maybe something wrong on my side.
