### ISSUE TITLE
Rendered options not updated on dropdown close / open

### ISSUE THREAD

**Issue by Cedricvb** [sanusart/react-dropdown-select#133]
When searching the options in the dropdown, the options shown are narrowed down as expected. If you then click outside the element, the search input is cleared. This is also still expected behavior I think. But when you click the input field again, the dropdown opens with the previous search results.
I think this is unexpected behavior and it causes more complex issues in my own implementation as well.

**Comment by sanusart** [comment]
This is regression in v4.6.0, 
4.5.2 works as expected in this regard

**Comment by sanusart** [comment]
@pattiereaves if you'll have a chance to check it, if not I'll get to it soon enough.

**Comment by pattiereaves** [comment]
I can take a look in the next day or two.
