### ISSUE TITLE
Unique Key Prop Warning for nested value field.

### ISSUE THREAD

**Issue by pgegenfurtner** [sanusart/react-dropdown-select#137]
My select has a nested valueField (`manufacturer.id`) and I get a unique key prop warning from react.

It seems that the key prop from the Dropdown component does not handle this properly.

Or am I doing something wrong or missing something?

Thanks!

**Comment by sanusart** [comment]
Make sure the values that gets into the select are unique. This are used internally as a key on the options list.

**Comment by pgegenfurtner** [comment]
The values are unique. I pass an array of objects to the options prop. The values inside the objects are all different.

My setup looks like this: 

```
possibleOptions = [
  {
    "id": 3,
    "ecommerce_settings_id": {
      "id": 1
    },
    "manufacturer_id": {
      "id": 5,
      "display_name": "Maurice Lacroix",
      "slug": "maurice-lacroix"
    },
    "sort": null
  },
  {
    "id": 4,
    "ecommerce_settings_id": {
      "id": 1
    },
    "manufacturer_id": {
      "id": 7,
      "created_on": "2020-11-03T13:12:45+00:00",
      "display_name": "Fossil",
      "slug": "fossil"
    },
    "sort": null
  }
]


<Select
        multi
        searchable
        keepSelectedInList
        labelField='manufacturer_id.display_name'
        valueField='manufacturer_id.id'
        searchBy='manufacturer_id.display_name'
        closeOnSelect
        closeOnScroll={false}
        css={dropdownStyle}
        name='manufacturersFilter'
        values={manufacturersFilter}
        options={possibleOptions}
        placeholder='Hersteller'
        onChange={values => onChangeFilter(values)}
        disabled={possibleOptions.length === 0}
      />
```

Interestingly, the value that I get on change is the whole object; not only `manufacturer_id.id` like specifieid in valueField. Is my expectation false?

**Comment by pgegenfurtner** [comment]
Okay, after trying something, I fixed my issue. I reduced the depth of the objects in the array, so the value I want to use is not nested.

The problem is, that the dot notation does not work.

**Comment by sanusart** [comment]
Hmmm. Nested values should work as they are working in the examples demo.
I'll check later this week, unfortunately my laptop died and refuse to
reinstall the OS.

Getting the whole object is expected if you pass the whole object in the
options.

**Comment by pgegenfurtner** [comment]
Ooookay. No stress for me.
Thank you for your time!
