### ISSUE TITLE
Dropdown "selected value" breaking in two lines due to "input"

### ISSUE THREAD

**Issue by waterizzet** [sanusart/react-dropdown-select#138]
Hello,

I recently update to the latest version of react-dropdown-select and the dropdown started to display a blank space under the selected value when:
- the dropdown has a small width and/or the selected value is large enough
- `searchable` is set to false

You can easily check this issue in the official demo page:
![image](https://user-images.githubusercontent.com/32458532/98029336-553d7100-1ddd-11eb-82b1-74ac674f596b.png)

This issue seems to be caused by the following change, that removed the width from the input element for version 4.5.0:
https://github.com/sanusart/react-dropdown-select/commit/6c07893803697572881be7ed300e059b32504fbb#diff-355dd90b189a371d7897f486b96c49320ab551e204525189105994d501655cbe
![image](https://user-images.githubusercontent.com/32458532/98029746-ffb59400-1ddd-11eb-914d-13479aafeea0.png)

Thank you! First time reporting an issue, let me know if you need more information

**Comment by sanusart** [comment]
Thanks, great first issue reporting BTW.

Regression by: https://github.com/sanusart/react-dropdown-select/issues/114

**Comment by smondal1234** [comment]
this is still happening on version 4.8.4

**Comment by sanusart** [comment]
> this is still happening on version 4.8.4

Can you please provide example?
