### ISSUE TITLE
how to get the key value only instead of whole array?

### ISSUE THREAD

**Issue by feiraelectronica** [sanusart/react-dropdown-select#139]
Hi @sanusart ,
currently if i do this

onChange={values => this.setValues(values)}

the values will return this,
[{"value":"M","label":"Male"}]

I just want the value M instead of the whole array to be stored in the database

how do I do it?

**Comment by feiraelectronica** [comment]
and if for multiple, 
[{"value":"MY","label":"Malaysia"},{"value":"CHI","label":"China"},{"value":"AUS","label":"Australia"} ]

i need the value to be, 'MY', 'CHI', 'AUS'. 

please help me masta @sanusart . 

thank you

**Comment by sanusart** [comment]
This is not related to this component. 
You can use Array.map to getwhatever you need from the values on change. 

E.g. values.map(item => item.value)

**Comment by feiraelectronica** [comment]
> values.map(item => item.value)

thank you. it works.
