### ISSUE TITLE
Typescript file for react-dropdown-select

### ISSUE THREAD

**Issue by barakjobs** [sanusart/react-dropdown-select#140]
Can you please share the typescript file for this component?
So I can download it from the command npm install @types/react-dropdown-select.

**Comment by sanusart** [comment]
https://github.com/sanusart/react-dropdown-select/blob/eccff4c79372ca1e8a6050c5ef56f5c33f21a085/package.json#L7

**Comment by barakjobs** [comment]
can you please tell me the command to install this file.

**Comment by sanusart** [comment]
In get installed with the package.
You can find in in node_modules/react-dropdown-select/types.d.ts after npm install

**Comment by barakjobs** [comment]
I want to use checkbox in dropdown values. 
I am using itemRenderer props which is here: https://codesandbox.io/s/p54p8y1987?autoresize=1&file=/src/index.tsx
itemRenderer={
                this.state.itemRenderer
                  ? (item, itemIndex, props, state, methods) =>
                      this.itemRenderer(item, itemIndex, props, state, methods)
                  : undefined
              }

but I am getting below error while using

Type '(item: any, itemIndex: any, props: any, state: any, methods: any) => any' is not assignable to type '({ item, itemIndex, props, state, methods }: SelectItemRenderer<never>) => Element'.ts(2322)
types.d.ts(143, 3): The expected type comes from property 'itemRenderer' which is declared here on type 'IntrinsicAttributes & SelectProps<never>'

can you please help me on this.
https://codesandbox.io/s/p54p8y1987?autoresize=1&file=/src/index.tsx here also this is the same error. on line number 244.

**Comment by sanusart** [comment]
Look at the error you getting from ts. It is telling you exactly how it
should be used. The function accepts an object, and not just a list of
arguments.

**Comment by barakjobs** [comment]
can you please help me to define the type. how we can pass object here?

**Comment by barakjobs** [comment]
After changing the type in file tsx file. I am getting same error:

Type '(item: object, itemIndex: number, props: SelectProps<object>, state: SelectState<object>, methods: SelectMethods<object>) => JSX.Element' is not assignable to type '({ item, itemIndex, props, state, methods }: SelectItemRenderer<never>) => Element'.ts(2322)
types.d.ts(143, 3): The expected type comes from property 'itemRenderer' which is declared here on type 'IntrinsicAttributes & SelectProps<never>'

**Comment by sanusart** [comment]
It should be `({ item, itemIndex, props, state, methods }) => func()`,
not `(item, itemIndex, props, state, methods) => func()`

**Comment by barakjobs** [comment]
But in this example https://codesandbox.io/s/p54p8y1987?autoresize=1&file=/src/index.tsx.
 optionRenderer={
                this.state.optionRenderer
                  ? (option, props, state, methods) =>
                      this.optionRenderer(option, props, state, methods)
                  : undefined

**Comment by barakjobs** [comment]
Thanks for your help. It is working as expected in my system.
Can you also help me to get the dropdown render data as group with its title.?

**Comment by barakjobs** [comment]
I Want to change the color of check box from blue color to any other color. 
Can you please help me on that

**Comment by sanusart** [comment]
Use color prop
