### ISSUE TITLE
Backspace delete does not work on non-multi selects

### ISSUE THREAD

**Issue by Cuzzo01** [sanusart/react-dropdown-select#141]
Can be reproduced in the first example on the examples page.

[Link](https://sanusart.github.io/react-dropdown-select/examples/#Basic-(using-react-live))
Steps:
1. Select option.
2. Open select again and hit backspace.
(From my own testing this applies regardless of if clearable is set or not)

I would expect it would either clear the selected value, or in searchable selects it could start deleting characters and searching.

**Comment by sanusart** [comment]
I do not agree that should be the behavior for non multi select, but feel free to prove me wrong.

**Comment by Cuzzo01** [comment]
As far as I can tell there's no way to clear a non-multi select with the keyboard. It seems the only way is clicking the 'x' if it's `clearable`, or if you were to override `handleKeyDownFn` and code it on the delete key being pressed.

This makes searching difficult because a select that already has a value wont be able to search for a new one unless the 'x' is clicked. I think the natural tendency to clear it is to hit backspace and the prop `backspaceDelete` fits the behavior perfectly, while it currently doesn't have any meaning when not on a multi select.

Like I said in the first comment, I think the behavior could be either:
 - completely clearing the selected value (as it does on a multi with only one selected value)
 or
- just starting a search with the currently selected value and just deleting the last character 
would be a clean way to handle it.

**Comment by sanusart** [comment]
You have a point there. I completely forgot about backspaceDelete prop to be honest.
Yes. I think we should allow clearing it.

**Comment by sanusart** [comment]
available since v4.7.1
