### ISSUE TITLE
clearOnSelect doesn't seem to work

### ISSUE THREAD

**Issue by Cuzzo01** [sanusart/react-dropdown-select#142]
Can also be verified on examples.

[Link](https://sanusart.github.io/react-dropdown-select/examples/#Basic-(using-react-live))
Steps:
1. Adding `clearOnSelect` to either the linked example or the one below doesn't have an effect.

Edit: reading through the code, it seems this is supposed to only apply to the search box. With how the search and selected values are rendered in the same space, I assumed it would extend to the selected value as well.

**Comment by sanusart** [comment]
This is description from the api:
> If true, and searchable, search value will be cleared upon value select/de-select

**Comment by Cuzzo01** [comment]
Fair enough.

In the case of a mutli I could see how this would cause problems. Somewhat related to the other issue I opened but on a non-multi, this does cause some strange functionally. It doesn't clear the selected value so even though the search is cleared, the search string is typed behind the previously selected value. (can be seen on the first example) 

While I don't think this would be bad functionality, its easy enough to use `onDropdownOpen` to clear the selected value in this case.
