### ISSUE TITLE
Options don't have selected state.

### ISSUE THREAD

**Issue by Roman-Samuilov** [sanusart/react-dropdown-select#146]
I'm using JAWS scan reader and options don't give information about selected state. Perhaps, the aria-selected attribute can fix this issue.
Desired behavior - when focusing on an element, it is announced whether it is selected or not.

**Comment by Roman-Samuilov** [comment]
In addition to this issue, I would like to see the implementation of the sound of the opening and closing. Aria-expanded could solve this.

**Comment by sanusart** [comment]
@Roman-Samuilov  thank you for suggestion and feedback, added aria-expanded, aria-selected was already present on component with role="list"

**Comment by sanusart** [comment]
available since v4.7.2
