### ISSUE TITLE
react-dropdown-select and react-hook-form

### ISSUE THREAD

**Issue by seenitall** [sanusart/react-dropdown-select#152]
Considering that you are extending the flexibility of react-relect library, I would expect it to work with react-hook-form. 

I attach three examples: an standalone react-dropdown-select, an attempt to make it work with Controller, and the counterpart "react-select" component working with Controller.

https://codesandbox.io/s/epic-feather-4szdr?file=/src/App.js

**Comment by sanusart** [comment]
From reading the statement abobve I feel the need to write this to dissolve any confusion there might be: I don't know where you get this expectations from, regarding any connection to react-select, but there is none. This is stand alone solution, totally custom and with different way of implementation. It is in no way better or worst than react-select. It is another solution to solve customized dropdown, not an extension and not aiming or stating to be better or worst in any way. 

Now if there is anything that this package is not compatible with, we can see how it can be fixed, but no comparison should take place.

**Comment by sanusart** [comment]
oops. did not meant to close it.

**Comment by seenitall** [comment]
All right, thanks for the clarification. Both libraries are quite good, so now that expectations are lowered down, let's see if you/anyone has any intuition about, if possible, how to make this one work with react-hook-form, as it is widely used. If it helps, and as its documentation states, what it requires is the "ref" prop of the .js component being exposed.

**Comment by sanusart** [comment]
It's actually has a ref:
https://github.com/sanusart/react-dropdown-select/blob/master/src/index.js#L507

**Comment by seenitall** [comment]
Ok, not sure if it would be that straightforward, but then would be a matter of exposing it in the props of the Select component (https://github.com/sanusart/react-dropdown-select/blob/381b34b3206727aadec65f0b7bfe08343adbd1ec/src/index.js#L26).
