### ISSUE TITLE
Disable opening on clearing contents

### ISSUE THREAD

**Issue by Johnne25** [sanusart/react-dropdown-select#156]
If you click the 'x' to clear the contents drop down is still opened.

It should always only open when you start typing in the field or click the down arrow button.
Otherwise you can have a property called 'openOnClick set to true which will open the dropdown if the user clicked the control (but not clicking the 'x').

**Comment by sanusart** [comment]
You can override clear button using clearRenderer https://sanusart.github.io/react-dropdown-select/prop/clear-renderer
