### ISSUE TITLE
Dropdown needs to be Accessible

### ISSUE THREAD

**Issue by Johnne25** [sanusart/react-dropdown-select#157]
So far this is one of the better dropdown menu implementations I have seen.
I would be fantastic if you could make it a bit more accessible (used with keyboard only).

So far I haven't been able to get it to function correctly without using the mouse.

Here is what would be nice to have fixed:
1. Tabbing into the dropdown doesn't show the cursor in the input area.
2. Pressing the down arrow does open the dropdown, however you can not navigate the dropdown list (using up and down arrows).
3. Pressing enter does select the item.
4. Once into the control, you can not tab out of it.

**Comment by sanusart** [comment]
1. It is bu design and constrains of being able to skip the field. Tapping down will.
2. it does navigate with both, arrows and tabs
3. What is wrong with that?
4. Escape

**Comment by Johnne25** [comment]
Ok.
#1. I will agree with.  Not a big deal.
#2. I have tried and once I press the down arrow to open the dropdown list I can not navigate to it.  Pressing TAB or all the arrow keys does nothing.
#3.  Sorry, it was to indicate pressing ENTER does work correctly, wasn't an issue.
#4.  Ok, pressing ESC does work.

So, only #2 doesn't work for me.

**Comment by sanusart** [comment]
May I ask the browser kind and Operating system to debug number 2?

**Comment by Johnne25** [comment]
The backend is running on a Windows 2019 machine (node.js).
The frontend is running on a Mac (node.js).
The browser is running on a Mac Big SURR Beta 3 (same as the frontend server).
The browser is the latest version of Chrome.

**Comment by sanusart** [comment]
Unfortunately I was not able to reproduce. Same env described just the stable, latest version of big sur.
