### ISSUE TITLE
Altering values doesn't update view after using selection from dropdown

### ISSUE THREAD

**Issue by funkenholy** [sanusart/react-dropdown-select#158]
When programmatically updating the selected value used in the react-dropdown-select element, the value displayed on the dropdown will no longer update when programmatically changed after manually selecting an item from the dropdown list.

I've looked through your example at https://sanusart.github.io/react-dropdown-select/examples#External-clear-and-add and I am not able to replicate the issue I'm experiencing, so I've created a similar setup to what I'm trying to achieve on codesandbox.

https://codesandbox.io/s/withered-meadow-jqge9?fontsize=14&hidenavigation=1&theme=dark

In the example, if you type inst1, inst2 or inst3 into the input field, the react-dropdown-select will update to that value as expected.
But if you then make a selection manually using the dropdown list and then try change the value in the input to inst1, inst2 or inst3, the dropdown list does not update even though the value in state is updated.

I don't think this is a bug with react-dropdown-select but is more likely something to do with how I'm trying to use it.
Any help would be greatly appreciated.

**Comment by brownmessiah** [comment]
Hey @funkenholy , 

instead of changing the state programmatically, try using methods.addItem() to add the item

**Comment by sanusart** [comment]
Hope helps https://codesandbox.io/s/quizzical-grass-x1o6q

**Comment by funkenholy** [comment]
Thanks Sasha, I found some time today and was able to adapt what you have in your example into mine, and then into my actual project.

https://codesandbox.io/s/dreamy-swirles-1yu0w?fontsize=14&hidenavigation=1&theme=dark

Appreciate your time.
