### ISSUE TITLE
Overriding default styles

### ISSUE THREAD

**Issue by irogozhova** [sanusart/react-dropdown-select#159]
When adding custom className, my SC styles get overridden by the library styles. Right now it can be fixed by manually increasing specificity (adding && inside the SC rule, or parent selector, or important rule), but it doesn't seem like a clean solution. Is it possible to make styles added with custom className override defaults? For example, Material UI solves this with injectFirst attribute in their StylesProvider.

**Comment by sanusart** [comment]
This just a small isolated component. While it is using emotion at the moment it will be overkill to expose emotions provider. 
Now classes are provided to nest in styled wrapper. 
However if you think of a clean solution without compromising size too much and fording this component to css in is of any kind I am open to ideas.
