### ISSUE TITLE
Not consider accents onChange

### ISSUE THREAD

**Issue by alfredoflexicar** [sanusart/react-dropdown-select#161]
is it possible that accents are not considered?

when writing, the dropdown only shows matches, but takes accents into account,
is it possible to ignore this?

**Comment by sanusart** [comment]
You can override the searchFn to match whatever you need. Will that work?

**Comment by alfredoflexicar** [comment]
how can i do that?

**Comment by sanusart** [comment]
https://github.com/sanusart/react-dropdown-select/blob/master/docs/src/examples/WithSearchFn.js
