### ISSUE TITLE
Should props.options update call searchResults() ?

### ISSUE THREAD

**Issue by voneiden** [sanusart/react-dropdown-select#162]
https://github.com/sanusart/react-dropdown-select/blob/fae4c984cbbe39d8ff4ee89f0c8c62a9290b5320/src/index.js#L135

Would it be more appropriate if this was rather

`this.setState({ searchResults: this.searchResults() });`

?  In my use case, I need to update options dynamically from a large external source while typing and while that works fine, the current behaviour clears the search even though the input field is not empty. I've done this modification locally and my first impression is that it appears to work OK. Ping @pattiereaves 

(In case someone is wondering how I hook into the input events as there does not seem to be an obvious way to do this [or I missed it]: I provide searchFn function via props which triggers a callback but returns undefined like the defaultProps implementation. react-dropdown-select then calls its own internal searchFn handler afterwards https://github.com/sanusart/react-dropdown-select/blob/fae4c984cbbe39d8ff4ee89f0c8c62a9290b5320/src/index.js#L381 )

**Comment by sanusart** [comment]
Would you be willing to prepare a PR. My hands are full at the moment

**Comment by voneiden** [comment]
Sure, I'll handle that.

**Comment by sanusart** [comment]
Thanks you @voneiden, bublished v4.7.4
