### ISSUE TITLE
Nested options aka childrens so we make it react-dropdown-tree-select

### ISSUE THREAD

**Issue by Mako-L** [sanusart/react-dropdown-select#164]
Do we have an example with nested options?
like this repository has : https://github.com/smitpatel1010/multi-select-tree

**Comment by sanusart** [comment]
Not out of the box

**Comment by Mako-L** [comment]
I'll try combining them see where i get :1st_place_medal:

**Comment by sanusart** [comment]
I mean using custom renderers of this you probably can get a tree structure. But I am not sure it is worth the effort, especially when ready solution are made for tree structures.
