### ISSUE TITLE
Simple setup not working?

### ISSUE THREAD

**Issue by douglasrcjames** [sanusart/react-dropdown-select#167]
No idea how I am messing this up, but the items are not appearing in my select menu, they seem to be white text, invisible, or I don't know. You can click items and the console log shows the item clicked. When you click the select again, all items are highlighted. 

Here is my code sandbox as simple as possible: https://codesandbox.io/s/dawn-brook-tgdyj?file=/src/App.js

**Comment by sanusart** [comment]
You need to map some of the options properties to label and value. Or use
props provided to tell the select what is the key of the value and what is
the key for the label

**Comment by sanusart** [comment]
Hey, You need to map some of the options properties to label and value. Or use props provided to tell the select what is the key of the value and what is the key for the label

**Comment by douglasrcjames** [comment]
Gotcha, I fixed it by adding the props `labelField={"name"}` and `valueField={"name"}` to the `<Select />` component. It seems these two props are necessary for the minimum viable setup, so I feel these should be mentioned in the docs more clearly as I was searching for a while!

**Comment by sanusart** [comment]
Not nessesery. You also can have the data mapped. Label and value are just the defaults. This props exist to allow to remap the data without tampering with it. Or in cases where label or value are nested in the data.
