### ISSUE TITLE
Hidden Select will not correclty render dropdown options on visibility change

### ISSUE THREAD

**Issue by HiagoQualitas** [sanusart/react-dropdown-select#168]
Steps to reproduce:

- Create a hidden div with a dropdown inside it
- Create button to toggle visibility of the div

Expected behaviour:

- Select and dropdown visible and working

Actual behaviour:

- Selectbox visible but when clicked, not correctly renders dropdown options

4.7.4 tested on React

**Comment by dannynpham** [comment]
I was getting the same issue too. I solved it by using the CSS `visibility` property to toggle the visibility of the component. It seems like the dropdown is created asynchronously, so when the parent is hidden the dropdown doesn't inherit the width correctly.

**Comment by sanusart** [comment]
The parent is hidden or the parent is not mounted yet?

**Comment by dannynpham** [comment]
The parent should be hidden as far as I can tell. I was using `display: none`.

**Comment by dannynpham** [comment]
@sanusart I reproduced it in this [CodeSandbox](https://codesandbox.io/s/react-dropdown-select-forked-v5qbc?file=/src/index.tsx)

**Comment by sanusart** [comment]
Have you tried to force it to rerender after visibility change?  A
different key prop will do I think.

**Comment by dannynpham** [comment]
Yea that was the solution I came up with. I rerender it using a `visible` prop. It's not ideal though.

**Comment by sanusart** [comment]
The problem is that it measure stuff on load but not on resize. Not sure it
is worth to add more listeners just for this.
