### ISSUE TITLE
clearing one item clears all items from multi select. selecting one item marks all others as selected 

### ISSUE THREAD

**Issue by ishaisagi** [sanusart/react-dropdown-select#176]
I have a select with multiple items selected. when I click the "x" next to one of the items (not the global one), the entire box is cleared instead of the one I clicked on.
if I clear all items, I can open the dropdown and select another item. however ,at that point I cannot open the dropdown again - the other items disappear.
If I remove the "keepSelectedInList={false}" the problem becomes clearer - selecting one item does show it as selected in the text area, but when re-opening the dropdown, all other items are showing as selected as well.

 <Select
                                        loading={this.state.docs.length == 0} searchable={true}
                                        multi={true} clearable={true} className={[Styles.fieldControl, Styles.reactSelect].join(" ")}
                                        closeMenuOnSelect={false} keepSelectedInList={false}
                                        onChange={selected => {                                            
                                            this.setState({
                                                supersededRegIDs: selected
                                            });
                                        }}
                                        values={
                                            this.state.docs.length > 0 ?                                                                                            
                                                this.state.supersededRegIDs:
                                                []
                                        }
                                        options={this.state.docs}>
                                    </Select>

**Comment by sanusart** [comment]
Hey, selected, the parameter returning by onChange is an array of objects.
`[{}]`

Is that helps?

**Comment by ishaisagi** [comment]
Hi Sasha,
it doesnt help - the documentation states that this is what is expected to be returned:
"On values change callback, returns array of values objects"
https://www.npmjs.com/package/react-dropdown-select

so it returns an array of values of objects, which should be what is selected. I tried adding a "return selected" at the end of the onchange code, but it doesnt change the behaviour

**Comment by ishaisagi** [comment]
found the issue. I had to include 
labelField="label"
valueField="key"

it would be good to have documentation about this...

**Comment by sanusart** [comment]
Great. Yes need to specify more clearly. 😊
