### ISSUE TITLE
How can we show the selected/particular option to be visible

### ISSUE THREAD

**Issue by mano-balakrishnan** [sanusart/react-dropdown-select#180]
When the dropdown has more than 100 items. How can we show the selected/particular option to be visible in the screen.
<img width="1440" alt="Screenshot 2021-06-07 at 8 49 56 PM" src="https://user-images.githubusercontent.com/54625880/121043103-f6583400-c7d1-11eb-936e-fcaa9c443e04.png">
<img width="1440" alt="Screenshot 2021-06-07 at 8 50 02 PM" src="https://user-images.githubusercontent.com/54625880/121043162-01ab5f80-c7d2-11eb-87ad-918c10f089d2.png">

**Comment by sanusart** [comment]
I guess it can be scrolled into view. But how to deal with multiples? Any
suggestions?

**Comment by mano-balakrishnan** [comment]
I think existing behaviour is fine for deal with multiples. but it would be better if we have something different for single select.

**Comment by sanusart** [comment]
Yes, I agree.
