### ISSUE TITLE
All dropdown items selected after selecting only one

### ISSUE THREAD

**Issue by georgiossalonad** [sanusart/react-dropdown-select#183]
After only selecting one dropdown item and then re-opening it (clicking on the dropdown) all items in the dropdown are selected and have the following css properties (marked as blue with white text):

```
.css-148o527-ItemComponent.react-dropdown-select-item-selected {
    background: #0074D9;
    color: #fff;
    border-bottom: 1px solid #fff;
}
```

Here is how I implemented the Select component:
```

<Select
    options={
        unselectedUsers[0] !== undefined
         ? unselectedUsers
          : []
    }
    values={
      voter?.user?.uid === "" ? [] : [...[voter.user]]
    }
    onChange={(user) =>
      saveVoter(user[0]?.uid, group.id, dropdownIndex)
    }
    labelField="fullName"
    searchBy="fullName"
    placeholder="Select Voter"
    sortBy="fullName"
    required
/>
```

Only one dropdown item should be visible and selectable.

**Comment by sanusart** [comment]
values need to be array of objects I think

**Comment by georgiossalonad** [comment]
Right. 

Which they are: 
`[...[voter.user]]`

`voter.user` is an object in my code

**Comment by georgiossalonad** [comment]
Found it... I had to use the `valueField` property
