### ISSUE TITLE
Center Selection

### ISSUE THREAD

**Issue by github-jeff** [sanusart/react-dropdown-select#184]
What is the correct method to center the default value or selected value?  I'm using tailwind but this question probably translates to any flavor of css.

The dropdown choices respond to css via the classname string as expected, but while the selected option responds to text size/color etc. the position of the selected element does not seem to follow css rule.

For example no matter what I seem to do the selected choice is align left or align right which is overriding css.  These options are called on the direction option as "ltr" or "rtl", which is ok, but there does not seem to be a centered option.

Any help would be appreciated.

```
<div className="col-span-3 row-span-2 py-10 border-black border-l-2 border-t-2">
     <Select
          onChange={(value) => onDropChange(value)}
          name="TestName"
          options={testOptions}
          value={testRequest.TestName}
          searchable={true}
          className="text-3xl text-center my-4 focus:outline-none w-full font-light text-gray-500 placeholder-gray-500 y-2"
     />
</div>
```

**Comment by sanusart** [comment]
.react-dropdown-select-content is flex-box. Adding:

```
flex-direction: column;
align-items: center;
```

To it, should center the selected value

**Comment by github-jeff** [comment]
Thank you for your response.  The method, appears to be the right reference.  Unfortunately it does not seem to work in this case.  Where, or how, am I supposed to implement this method?

Here is a code sample from the application.  There is a parent container and two child items.

```
<div id="Compatibility Block" className="grid grid-cols-6">
     <div className="text-l font-semibold col-span-2 pl-4 pb-4">
          <Select
               onChange={(value) => onDropChange(value)}
               name="CompatibilityType"
               options={compatibilityOptions}
               value={testRequest.CompatibilityType}
               className="text-lg text-center my-4 focus:outline-none w-full font-light text-gray-500 placeholder-gray-500 y-2"
          />
     </div>
     <div className="text-xl font-semibold col-span-2 pb-4"></div>
     <div className="text-l font-semibold col-span-2 pr-12 pb-4">
          <Select
               onChange={(value) => onDropChange(value)}
               name="UrgentFlag"
               options={urgentOptions}
               value={testRequest.UrgentFlag}
               className="text-lg text-center my-4 focus:outline-none font-light text-gray-500 placeholder-gray-500 y-2"
          />
     </div>
</div>
```
I have tried specifying flex on the parent container.

`<div id="Compatibility Block" className="flex flex-col items-center grid grid-cols-6">`

and then the tried the same on both the child div

`<div className="text-l font-semibold col-span-2 pl-4 pb-4 flex flex-col items-center">`

as well as on the Select item directly

`className="text-lg text-center my-4 focus:outline-none w-full font-light text-gray-500 placeholder-gray-500 y-2 flex flex-col items-center"`

I have also tried various combinations of the above but it does not seem to be working.  I must be doing something incorrectly.  How would you structure the css here?

**Comment by sanusart** [comment]
It is inner component so it need to be styled via css.

The other option is to override the content renderer with own div, then
you'll be able to apply classes to it.

Does that helps?

**Comment by github-jeff** [comment]
Honestly not really.  I have put the flex and related everywhere I can think of.  It must be super obvious and I'm just missing it.

**Comment by sanusart** [comment]
No, what I meant is you need to override the properties of the inner class
called ".react-dropdown-select-content".

**Comment by github-jeff** [comment]
Now I understand.  For those that are following along:

`<div className="!important col-span-3 row-span-2 py-10 px-4 border-black border-l-2 border-t-2 !important flex flex-col items-center">`

The key here is the `!important` tag.  It's well ... important enough to override parent css.

So while this technically solved the problem, it presents another.  The dropdown is now centered but it is not following the col-span rules.  In this case, the dropdown is only as wide as the current selected value and naturally varies in width.  Therefore, if the user initially chooses something short in character length, but then changes the selection later, the dropdown options are all swished together.

How do I expand the width of the dropdown with the override still active so the element expands to fill the available column (keeping px-4) would be nice as well.

**Comment by sanusart** [comment]
This is why I also suggested to override the selected value with contentRenderer check out this one https://codesandbox.io/s/react-dropdown-select-forked-lbgnz?file=/src/index.js:275-278

**Comment by github-jeff** [comment]
.... and just like that we are done.  Many thanks.  For those following along, the above sandbox is the complete solution and works great.  In my application is looks like the following.

My options are in a separate file, hard coded for now, but will eventually be called from a database.
```
const testOptions = [
    {
        label: 'Shown Test Name 1',
        name: 'Database Column Name 1',
        value: 'Database Test Name 1'
    },
    {
        label: 'Shown Test Name 2',
        name: 'Database Column Name 2',
        value: 'Database Test Name 2'
    }
];
export default testOptions
```
Then in the main function

```
function CreateTestRequest() {
...
```
This section goes somewhere above the return
```
const customContentRenderer = ({ props, state }) => {
        // see the style prop
        return (
          <div style={{ textAlign: "center", width: "100%" }}>
            {state.values[0].label}
          </div>
        );
};
```
Then in the return section

```
<div className="!important col-span-3 row-span-2 text-3xl py-6 px-4 border-black border-l-2 border-t-2 flex flex-col text-center">
     <Select
          onChange={(value) => onDropChange(value)}
          name="TestName"
          options={testOptions}
          value={testRequest.TestName}
          values={[testOptions[0]]}
          searchable={true}
          contentRenderer={customContentRenderer}
          className="!important col-span-3 text-xl font-semibold my-4 focus:outline-none w-full placeholder-gray-500 y-2"
     />
</div>
```
**Note:** I am using value for the selected option to the database and values to pull the css.  This is likely to change for maintenance reasons but for now just know `value=` is very much not the same thing as `values=`.
