### ISSUE TITLE
Changing height of the input field of the react-dropdown-select

### ISSUE THREAD

**Issue by ShauryaS** [sanusart/react-dropdown-select#185]
How can one change the height of the input field of the react-dropdown-select easily? Is there a straightforward way to do so?

**Comment by sanusart** [comment]
Css style

**Comment by ShauryaS** [comment]
is there a list of the ids and class names to know exactly which css style to modify?

**Comment by sanusart** [comment]
Just inspect with devtools

**Comment by ShauryaS** [comment]
Unfortunately, when inspecting with devtools and inspecting, it is not clear which css styles should be manipulated to change the height. Further help would be appreciated
