### ISSUE TITLE
Mantain placeholder as an option to clear the selection

### ISSUE THREAD

**Issue by ccalvarez** [sanusart/react-dropdown-select#186]
Hi, I have a not searchable dropdown select, it has a placeholder.

Is it possible, once an option is selected, to mantain the placeholder visible and clickable, to select it to clear all the selected values?

Thank you.

**Comment by sanusart** [comment]
Not out of the box as selected values will always appear as indicator.
But you can override the content of it using custom content renderer with
an input and placeholder and act upon interaction with it.

**Comment by ccalvarez** [comment]
@sanusart thank you.  I'm closing the issue.
