### ISSUE TITLE
Any way to do like Outlined dropdown field? refer screenshot in description

### ISSUE THREAD

**Issue by feiraelectronica** [sanusart/react-dropdown-select#189]
Hi, is there any way to do like this?

![image](https://user-images.githubusercontent.com/72189108/124887524-d3ef4b80-e007-11eb-9687-d5e5271a28c8.png)

thank you

**Comment by sanusart** [comment]
Style it with css

**Comment by feiraelectronica** [comment]
do you have an example?

**Comment by sanusart** [comment]
https://sanusart.github.io/react-dropdown-select/examples/#Styled

**Comment by feiraelectronica** [comment]
> https://sanusart.github.io/react-dropdown-select/examples/#Styled

Hm not exactly what I want. 

what i want is like this. the title move on top when dropdown is selected.

![image](https://user-images.githubusercontent.com/72189108/126125440-536fc517-32ad-42b7-ae4a-ad0bafb2a932.png)

**Comment by sanusart** [comment]
You will have to implement it yourself.

**Comment by feiraelectronica** [comment]
k
