### ISSUE TITLE
Encountered two children with same key

### ISSUE THREAD

**Issue by Kishrore** [sanusart/react-dropdown-select#19]
In your demo change the following:
searchBy : username to name
labelField : username to name
valueField: email to address

If the value field is json object then the demo is not working and shows the error "Encountered two children with same key"

So your library is not supporting the  json kind of value field

**Comment by sanusart** [comment]
Nope, Object as internal value is not supported. If you need the data of full object - it is there anyway, selected values are full, untouched object you pass as options.

**Comment by Kishrore** [comment]
Thank you, I fixed the issue

**Comment by sanusart** [comment]
@Kishrore thank you for taking time to report!
