### ISSUE TITLE
ClassName bootstrap

### ISSUE THREAD

**Issue by stonestecnologia** [sanusart/react-dropdown-select#192]
Hello !!! How are you?
How do I apply bootstrap class in the component ?

Thks

**Comment by sanusart** [comment]
Just pass className, nothing special

**Comment by sanusart** [comment]
additionalProps get passed to inner Select

**Comment by stonestecnologia** [comment]
> Just pass className, nothing special

Thank you for answering me.
I even tried it according to the documentation, but without success.
It didn't apply the css/bootstrap effects

`                <Select
                  className={"mb-2 form-control-sm form-control"}
                  options={selectSellers}
                  searchBy={"nomCad"}
                  labelField={"nomCad"}
                  valueField={"codCad"}
                  placeholder="Selecione um vendedor"
                  noDataLabel="Nenhum registro encontrado"
                />
`

**Comment by stonestecnologia** [comment]
> additionalProps get passed to inner Select

this way ?

`additionalProps={"class","mb-2 form-control-sm form-control"}`

**Comment by sanusart** [comment]
additionalProps={{className: "mb-2 form-control-sm form-control"}}

**Comment by pavangayakwad** [comment]
No luck! Am I missing something? using TailwindCSS. 

Please assist.

![image](https://user-images.githubusercontent.com/1834890/130151551-5fc8b6a8-4084-49c7-a2c9-9541053b3b6b.png)

**Comment by sanusart** [comment]
Not sure. Don't use that. But you should pass it to
additionalProps={{className: "your-class"}}

**Comment by sanusart** [comment]
Also this component is not rendering html select. It is more like a text
input if you look at the compiled jsx.

**Comment by pavangayakwad** [comment]
As you can see the output is fine, it is failing only to get the styles right.

![image](https://user-images.githubusercontent.com/1834890/130183216-72be1a32-b2d4-4aa2-86e2-d069a2cc507a.png)

**Comment by pavangayakwad** [comment]
I had to fix it by overriding the class names and it worked fine.  Thanks for your time.
