### ISSUE TITLE
Accessibility Issue: Form elements must have labels

### ISSUE THREAD

**Issue by ccalvarez** [sanusart/react-dropdown-select#194]
Hi.

I am using the[ axe DevTools Web Accessibility Testing extension](https://www.deque.com/axe/devtools/), and it reports this issue on the react dropdown select controls:

**_Form elements must have labels_**

More details about the issue: https://dequeuniversity.com/rules/axe/4.3/label?application=AxeChrome

You can scan the Examples page:

![image](https://user-images.githubusercontent.com/2665104/137384703-a0e4fab8-a91b-4f0e-9f49-8e2f8a5ab193.png)

Thank you very much for your help.

**Comment by sanusart** [comment]
Hi, I checked the issue and it is not a problem with the component, this component, same as any HTML input type need to be wrapped in label by consumer. 
e.g.

```
<label>
  <Select>
</label>
```

**Comment by sanusart** [comment]
Hey Carolina, this sounds strange. Any chance you can reproduce the case in
codesandbox?

**Comment by sanusart** [comment]
I wonder why. In any case thanks for the update!
