### ISSUE TITLE
Dropdown Click always display "No Unique Key" For Array Items

### ISSUE THREAD

**Issue by sgrobert** [sanusart/react-dropdown-select#197]
Hi there,

I'm trying out `react-dropdown-select` for the first time. I've been just testing the default codes for `itemRenderer` to build a custom item dropdown list. 

Though the component loads into view, every time I clicked on the `Select`, my console will constantly pop up the **"No Unique Key" For Array Items error** as below:

```
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `Dropdown`. See https://reactjs.org/link/warning-keys for more information.
b@webpack-internal:///./node_modules/react-dropdown-select/lib/components/Item.js:1:1829
Dropdown@webpack-internal:///./node_modules/react-dropdown-select/lib/components/Dropdown.js:1:1160
div
ReactDropdownSelect
div
b@webpack-internal:///./node_modules/react-dropdown-select/lib/components/ClickOutside.js:1:860
b@webpack-internal:///./node_modules/react-dropdown-select/lib/index.js:1:3178
div
div
div

...

```

I'm using the following codes and have also injected the `key` item. 

```

itemRenderer={({ item, methods }) => (
            <div key={item.label} onClick={() => methods.addItem(item)}>
              <input onChange={() => methods.addItem(item)} type="checkbox" checked={methods.isSelected(item)} /> {item.label}
            </div>
      )}

```

Hope you can help shed some light on what I might have done wrong or how to rectify it.

Thank you so much!

**Comment by sanusart** [comment]
Can it be that labels are not unique?

**Comment by sgrobert** [comment]
Hey @sanusart,

Thanks for the reply. 

I've even attempted just the following:

---

```
itemRenderer={({ item, itemIndex, methods }) => (
                    <div key={`${item.headerName}-${itemIndex}`}>
                        ...
                    </div>
                )}
```

The above combination still creates the error, even though it creates a unique entry for each item.

However, I am curious, as I'm unsure how the `itemRenderer` works. Does it re-render another copy into ROM or does it clear the memory before re-creating? As when I left the menu open for a while, it had a "double-print" of the keys, which I am guessing might have made the `key` **not unique**.

Or maybe I'm wrong, hope you might be able to enlighten me as well. Thanks!

**Comment by sanusart** [comment]
Any chance you can create such scenario in codesandbox?

**Comment by sgrobert** [comment]
Hi @sanusart,

Just managed to set one up. 

Here you go!

https://codesandbox.io/s/recursing-cherry-gguwq?file=/pages/index.js

**Comment by sanusart** [comment]
@sgrobert I see.
The problem is that Dropdown component, that renders Item or value of itemRenderer iterates already. This is why the warning.

**Comment by sanusart** [comment]
I think you will have to use dropdownRenderer https://sanusart.github.io/react-dropdown-select/examples/#Custom-Content-And-Dropdown-renderers to achive optionGroup stuff.

**Comment by sgrobert** [comment]
Hi @sanusart,

Thanks for the heads up!

Took me a little while to see how to get the `dropdownRenderer` working. 

Now it works perfectly without and errors. Appreciate your help on this! Awesome plugin option by the way!
