### ISSUE TITLE
Allow custom input value in the most basic usage

### ISSUE THREAD

**Issue by yairEO** [sanusart/react-dropdown-select#2]
First of all, awesome job. I am impressed.

See this demo:
https://sanusart.github.io/react-dropdown-select/examples

I would like to allow my users to fill any data they desire manually, while also allow the ability to select a pre-existing option from the dropdown.

The problem is, if a test is typed in the field, it disappears on the input's `blur` event...

Is there a solution to this?

Thanks!

**Comment by sanusart** [comment]
Thanks @yairEO 
I guess prop can be added to control input clear. I guess `clearOnBlur` and `clearOnSelect` or something.

> I would like to allow my users to fill any data they desire manually

Can you explain more on this, I don't really fully get it.

**Comment by yairEO** [comment]
I want the input to be able to accept any text typed into it, doesn't matter if the value is included in the dropdown list or not, it's not always desirable to limit the text to finite range or options.

Hopefully I've managed to explain this better

**Comment by sanusart** [comment]
Checkout the "Create new Entries" example on https://sanusart.github.io/react-dropdown-select/examples

Is that what you need?

**Comment by yairEO** [comment]
I've checked out all the demos thoroughly, and that's not what i want.. I do not want tags.
I want an input element with one single value which is not a tag..

I am the author of [Tagify](https://github.com/yairEO/tagify) and I do not need a tags script, but a script which specializes in dropdowns. 

I think I understand what's going on here... I was completely miss-lead by the name of this script.. I thought it's a dropdown component when in facts in a **tags** component.. It's just not what the name stands for, this is not a customizable select element, since none of the example mimic the `<select>` element behavior.

**Comment by sanusart** [comment]
How is that not select exactly.
https://codesandbox.io/s/3kx74jlp0m

**Comment by yairEO** [comment]
well, it is close..but I see some bugs:

Clicking the component doesn't show the dropdown. you must click exactly on the input and not on the actual container surrounding it, which is a major UX bug..

I'm clicking on some items and seeing a weird rendering:

![image](https://user-images.githubusercontent.com/845031/53304649-69973f80-3880-11e9-8103-4dbe705980a4.png)

-----

Anyway, I would like to have the ability to enter any text I desire.

Thanks

**Comment by yairEO** [comment]
I made a GIF of the weird stuff I saw:

https://gifyu.com/image/3LL2

**Comment by sanusart** [comment]
Thanks. I'll check out the bug and will add props to control the clear of
input on blur.

Have you checked https://github.com/JedWatson/react-select

Maybe it has what you need imolemented.

**Comment by sanusart** [comment]
And yes. Click on the element should open the drop-down. Thanks for the input and clarifications.

**Comment by yairEO** [comment]
Yes, I've checked many and we are currently using this one, which I strongly recommended against because it is exploding from bugs.

1000+ open issues... 

We have been using it for some months as part of my client's project and we are looking for a better replacement since it also has open issues with major bugs and the maintainer does not respond as fast and politely as you are :)

**Comment by sanusart** [comment]
Yes. That's exactly the reasons I started to work on this repo. Also had
very bad experience with overriding build in elements.

**Comment by sanusart** [comment]
I think I've fixed all mentioned weirdness. 
You can check them in if you want https://codesandbox.io/s/3kx74jlp0m if you have more suggestions feel free to list them, preferably in a separate issue.

**Comment by yairEO** [comment]
So what about the props you've mentioned earlier in the comments?

> `clearOnBlur` and `clearOnSelect`

**Comment by sanusart** [comment]
Forgot. Will keep this one open for now.

**Comment by sanusart** [comment]
Added in v2.1.1 via edc348eccba3188c2f5d3ffb531f6bcd1429e259
