### ISSUE TITLE
Adding duplicate items

### ISSUE THREAD

**Issue by davidpenso** [sanusart/react-dropdown-select#20]
When you add an item in multi this check will always return `-1`

`if (this.state.values.indexOf(item) !== -1) {`

since item is an object and values is an array of objects

it should be 
`this.state.values.findIndex(value => value.label === item.label) `

or similar you can't compare to objects like that in indexOf in Javascript

**Comment by sanusart** [comment]
Thanks for taking the time report and explore the cause @davidpenso 
Will be available in the next release.
