### ISSUE TITLE
Suggestion for `onChange` behavior

### ISSUE THREAD

**Issue by TheGooner93** [sanusart/react-dropdown-select#204]
Great work on this !

Suggestion: In case of the prop `multi` being set to `false` , I would think it makes sense for the `onChange` callback to return a single value/object instead of an array with a single element. However I also believe that this would be a breaking change; what do you think @sanusart  ?

**Comment by sanusart** [comment]
Hi, thanks for the suggestion. It is definitly something to think about, but it is most defenetely be braking change. Not sure such braking change is worth to introduce.

**Comment by TheGooner93** [comment]
Agreed.
