### ISSUE TITLE
How do I cancel the selected value

### ISSUE THREAD

**Issue by Harikrishnan-Prabhakar** [sanusart/react-dropdown-select#206]
I have selected an option from dropdown. For certain reason, I don't want the selected option. I want to change the selected option to some other option. How to do that?

Ex: I have a dropdown to select month.  The user selected month (say Jan) is not valid, since user is not allowed to select month before current date (assume current month is Feb). So I want to change the selected option to Feb when Jan is selected. My code sets the selected value properly to Feb, but the dropdown is not updated.

Pls note, I cannot disable the options in dropdown. When invalid option is selected I need to reset the option to some other valid option. Is this possible kindly update.

**Comment by sanusart** [comment]
https://sanusart.github.io/react-dropdown-select/examples#External-clear-and-add

**Comment by Harikrishnan-Prabhakar** [comment]
This dynamic update is not working, if you change the options on the onChange callback. I have created a sandbox to show the issue, please check.

https://codesandbox.io/s/external-clear-forked-nlot7

I think the problem happens because of the comparison in componentDidUpdate method, where we compare prevProps.values, prevState.values. I haven't debugged it, but just a thought.  I hope my requirement is a valid scenario. Kindly let me know your thoughts.

**Comment by sanusart** [comment]
Is it working for you on the example?

**Comment by sanusart** [comment]
Update the lib version on the sandbox. You using v3.x there

**Comment by Harikrishnan-Prabhakar** [comment]
The example is working fine. But the way I'm trying to use is slightly different from the given example. I have updated to the latest version "4.8.2." in the code sandbox and checked it. But, facing the same issue.

**Comment by sanusart** [comment]
I'd suggest to use side effect in that case
https://codesandbox.io/s/react-dropdown-select-forked-1qezi?file=/src/index.tsx
