### ISSUE TITLE
Dynamic options list pulled from API

### ISSUE THREAD

**Issue by aleksandar-polic** [sanusart/react-dropdown-select#207]
We have over 30000 records saved in the database which are used for populating options in react-dropdown-select component. As it takes a long time to get records from the database, we created a search endpoint that gets only the records that match the criteria.

Is it possible to utilize search mechanism of react-dropdown-select to accomplish this? 

We tried to store options we get from API in state, then call the API in custom SearchFn with state.search as a parameter, and then update the options state with new data. But this does not behave in the way we expected. Changes are not propagated in dropdown correctly, and we can see the results only when we change the search parameter. It seems like some async action is creating problems.

Example:
1. Select is empty, options are empty
2. "Te" is entered in search field
3. Dropdown shows No data
4. this.state.options has 2 elements  (Test1 and Test2)
5. "s" is added to search. Search string is now "Tes"
6. Dropdown shows 2 elements (Test1 and Test2)
7.  this.state.options still has 2 elements

**Comment by sanusart** [comment]
It this reflecting your use case?
https://codesandbox.io/s/react-dropdown-select-forked-ki9de?file=/src/index.tsx

(Please refresh if you get no results - this means quota exceeded as I used github users api with no auth)
