### ISSUE TITLE
Need to be able to pass id attribute to input to be able to link labels using for

### ISSUE THREAD

**Issue by voneiden** [sanusart/react-dropdown-select#209]
A `<label>` allows referencing an input field via input element id: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label#attr-for

Currently it is not possible to assign an id to the inner <input> created by `<ReactDropdownSelect>`. ( https://github.com/sanusart/react-dropdown-select/blob/master/src/index.js#L519 )

Therefore labels cannot reference 

I can do a PR if I get some feedback whether it be reasonable to add a new prop, for example `inputId` for this purpose? Or any other proposal?

Meanwhile I've made a naughty workaround with ref

```
        ref={(e) => {
          if (e?.select?.current) {
            // Sorry but not sorry
            const input = e.select.current.querySelector(`input[name="${name}"]`)
            input.id = `form-component--${name}`
          }
          inputRef(e?.select?.current)
        }}
```

**Comment by sanusart** [comment]
What is the main concern here?

It is also mentioned that

> Alternatively, you can nest the <input> directly inside the <label>, in
which case the for and id attributes are not needed because the association
is implicit:

<label>Do you like peas?
  <input type="checkbox" name="peas"></label>

**Comment by voneiden** [comment]
Nesting will bind the label with `<InputComponent/>` instead of the latter `<input>`. I thought this is a problem, but upon trying it a second time it seems to work just fine. Thanks. Case closed, nothing to see here.
