### ISSUE TITLE
Please upgrade to emotion 11

### ISSUE THREAD

**Issue by PolarBear292208** [sanusart/react-dropdown-select#210]
The latest version of emotion has renamed several packages:

[https://emotion.sh/docs/emotion-11](https://emotion.sh/docs/emotion-11)

This makes react-dropdown-select break if emotion 11 gets installed as a dependency with the error:

_Error: A new entrypoint in the @emotion/styled package, @emotion/styled/base, has replaced the @emotion/styled-base package. Please remove this package and use @emotion/styled/base instead._

A workaround is to explicitly include older versions of @emotion/core and @emotion/styled-base in my packages.json, but it would be nice to be on the latest version of emotion.

**Comment by isatanis** [comment]
+1

**Comment by sanusart** [comment]
done
