### ISSUE TITLE
Test with @testing-library/react

### ISSUE THREAD

**Issue by angiefrancop** [sanusart/react-dropdown-select#227]
I have not been able to find a way to test =

<Select
                    additionalProps={{id: id}}
                    data-testid="selectNova"
                    options={options}
                    placeholder="Seleccionar opción"
                    values={[value]}
                    onChange={(value) => onChangesHandleSelect(value)}
                />
I have not been able to find a way to test the onChanges function.

**Comment by sanusart** [comment]
https://github.com/sanusart/react-dropdown-select/blob/master/__tests__/index.spec.js#L78
