### ISSUE TITLE
Allow Custom Key Pre or Post

### ISSUE THREAD

**Issue by firrae** [sanusart/react-dropdown-select#23]
Currently, I am showing multiple Selects on the screen that offer the same options, this leads to React complaining about duplicate keys. There are no alternative options for me at this time, and while no specific issues occur at this time, allowing us to set a pre or post fix to the generated key would allow us the ability make them unique in this case. While it works now, I'd like to make sure it works into the future without warnings/errors.

I'm currently finishing up a project I'm on right now, after that is complete I can look at spending some time to try to implement something simple as a pull request if you like the idea and someone hasn't beaten me to it (or maybe there already is a solution I missed?).

**Comment by sanusart** [comment]
Hey @firrae this examples page https://sanusart.github.io/react-dropdown-select/examples loads multiple select elements. Most of them have same options, so I must believe the root of the warnings is not the same dataset.

Any chance you can share the dataset here for me to test and inspect? Or maybe you can reproduce this in https://codesandbox.io/?

**Comment by firrae** [comment]
I just played with some stuff and you seem to be correct. I thought it was the options but it seems to be something else potentially. I'll keep digging and see if I keep getting it and see if I can recreate it.

**Comment by firrae** [comment]
I believe you are correct after digging more. I will close this for now and continue examining it. I still have one page where I think the dropdowns are the only thing that might produce duplicate keys, but I'll keep looking.
