### ISSUE TITLE
Can not style grey placeholder text

### ISSUE THREAD

**Issue by Esylus** [sanusart/react-dropdown-select#234]
I've tried every CSS command that can be found, I can't seem to update the color or fontSize of the placeholder text.

In the StyledSelect 'style' object, some values, such as fontSize and fontFamily, affect both the placeholder and dropdown items together while other commands, such as fontWeight, only affect the dropdown items. 

Is there any way to independently change the placeholder color, size and fontWeight? 

Cheers,

![Screen Shot 2022-05-24 at 6 42 42 PM](https://user-images.githubusercontent.com/28571149/170160991-644badd0-841f-483d-aff3-78eed5d5007f.png)

**Comment by sanusart** [comment]
```
.react-dropdown-select input::placeholder {
  color: red;
}
```
