### ISSUE TITLE
Component not updating selected value on data change

### ISSUE THREAD

**Issue by alshdotme** [sanusart/react-dropdown-select#24]
Currently I've got two Select components on my page. The second select's options set depends on what option is selected in the first select component. When having selected something in the second components options and then swapping to another option in the first select, the second select box's options change however the currently selected item which is shown in the Select does not change. 

Is there a way to combat this? I'm not sure if I'm being stupid and missing the obvious.

**Comment by sanusart** [comment]
@alshdotme can you reproduce in codesandbox? You can for this one or something https://codesandbox.io/s/8n205nrmr8

**Comment by alshdotme** [comment]
Will sort one now for you. Thanks for the quick reply!

**Comment by alshdotme** [comment]
https://codesandbox.io/s/determined-turing-p03b1 -  @sanusart Sorry for the delay got caught up in a meeting. Here's an example.

**Comment by sanusart** [comment]
Will check it out ASAP. Thanks.

**Comment by alshdotme** [comment]
@sanusart Thanks. 

Steps to reproduce:

- Select top dropdown, choose Nissan
- Select bottom dropdown, choose Sunny
- Select top dropdown again, choose Volvo
- Sunny will now remain as the chosen option in the bottom select

**Comment by alshdotme** [comment]
@sanusart So it turns out it was my error. A very kind friend helped me to see my problem in the end.

Here's the solution: https://codesandbox.io/s/smoosh-voice-y1tcz

`function SelectInput({
  selected,
  options,
  labelField,
  valueField,
  onChange = () => {},
  label
}) {
  let value = options.find(o => o[valueField] === selected);

  if (!value) {
    value = options[0];
  }

  return (
    <>
      {label && <label className="select-input-label">{label}</label>}
      <p>{value.name}</p>
      <Select
        values={[value]}
        dropdownPosition="auto"
        onChange={selectOptions => onChange(selectOptions[0][valueField])}
        options={options}
        searchable={false}
        labelField={labelField}
        valueField={valueField}
      />
    </>
  )
}

function App() {
  const [state, setState] = useState({
    selectedMake: 0,
    seledctedModel: 0,
    remote: {
      makes: [
        { makeId: 0, name: 'ALL' },
        { makeId: 1, name: 'Nissan' },
        { makeId: 2, name: 'Volvo' }
      ],
      models: [
        { name: 'Quashqai', modelId: 1, makeId: 1 },
        { name: 'Sunny', modelId: 2, makeId: 1 },
        { name: 'V40', modelId: 3, makeId: 2 },
        { name: 'V50', modelId: 4, makeId: 2 }
      ]
    },
    filtered: {
      models: [
        { name: 'Quashqai', modelId: 1, makeId: 1 },
        { name: 'Sunny', modelId: 2, makeId: 1 },
        { name: 'V40', modelId: 3, makeId: 2 }
      ]
    }
  })

  const changeMake = makeId => {
    const nextState = {
      ...state,
      selectedMake: makeId,
    }

    if (!makeId) {
      nextState.filtered = { ...state.remote }
      return setState(nextState)
    }

    const models = nextState.remote.models.filter(
      model => model.makeId === makeId
    )
    
    nextState.filtered.models = models

    return setState(nextState)
  }

  return (
    <div className="App">
      <h1>Hello CodeSandbox</h1>
      <h2>Start editing to see some magic happen!</h2>

      <SelectInput
        selected={state.selectedMake}
        label="Choose a Make"
        options={state.remote.makes}
        onChange={changeMake}
        labelField="name"
        valueField="makeId"
      />

      <SelectInput
        selected={state.selectedModel}
        label="Choose a model"
        options={state.filtered.models}
        onChange={selectedModel => { setState({ ...state, selectedModel }) }}
        labelField="name"
        valueField="modelId"
      />
    </div>
  )
}
`

**Comment by sanusart** [comment]
Great. I might just add a kind of your use case to examples. Thanks for taking the time. 
Also please note the mutation on line 80 of the example.
