### ISSUE TITLE
searchFn accept async function?

### ISSUE THREAD

**Issue by firrae** [sanusart/react-dropdown-select#25]
Is there a way to have searchFn accept an async function or promise? All my API lookups use async functions and I can't seem to find any other function that will allow for the intercepting of the search to populate the values in the dropdown?

**Comment by firrae** [comment]
Also note, I can't just put all the items in the dropdown at once and search it there because there is something like 36k elements we need to search through.

**Comment by sanusart** [comment]
I don't really understand your usecase, but you can render custom drop-down with windowed list. See windowed example at https://sanusart.github.io/react-dropdown-select/examples/ it has 20000 or so items. 
searchFn is just a function override it can be whatever you want if overridden.

**Comment by firrae** [comment]
So we have a DB with ~120k items. What I'd like to do is pre-load ~500 which works fine, but then I'd like to override the searchFn to have it query the DB as the search. So as the user types their search query I can format the query to send to the server, send it, get a response with up to 500 matching items, and then set that as the list.

Currently, searchFn only seems to accept synchronous functions and with my client API layer doing queries in async (Promises) it doesn't do anything since it's async and searchFn is expecting a sync'd function.

**Comment by firrae** [comment]
When I try to load anything above 22k the Chrome tab locks up and then crashes so I can't just mass load all the options.

**Comment by sanusart** [comment]
The is no problem loading a lit of results using some kind of "virtualisation" solution as described in the example mentioned above, but you need to re-trigger api call based on search match. `searchFn` is just an override for search and sort of the results, not trigger for anything else 

https://github.com/sanusart/react-dropdown-select/blob/a04363e8e23f4a7d62f50ac32822da86c15abb9f/src/index.js#L325

I'd say for your use case you'd need to trigger your api call upon listening on changes on search (it is available as `state.search` in any overriden prop component like [dropdownRenderer](https://sanusart.github.io/react-dropdown-select/prop/dropdown-renderer) and then replace the `options` in your state.
