### ISSUE TITLE
"Select All" feature

### ISSUE THREAD

**Issue by jabdali** [sanusart/react-dropdown-select#251]
I wonder if "Select All" feature is supported to allow selecting all the options with one click?

**Comment by sanusart** [comment]
Available since v4.10.0

**Comment by singwithaashish** [comment]
Hi, how do i use it in react. the property selectAll doesn't exist. thanks

**Comment by sanusart** [comment]
https://react-dropdown-select.netlify.app/examples#With-select/clear-all

**Comment by singwithaashish** [comment]
It's not working in react vite and typescript. I am getting this err.. 

![image](https://github.com/sanusart/react-dropdown-select/assets/52033403/b5f7237b-4597-4f8c-8b30-01471faefa3d)


`Type '{ multi: true; selectAll: true; selectAllLabel: string; clearAllLabel: string; className: string; wrapperClassName: string; clearable: true; options: { value: number; label: string; }[]; values: { value: number; label: string; }[]; onChange: (values: { ...; }[]) => void; }' is not assignable to type 'IntrinsicAttributes & SelectProps<{ value: number; label: string; }>'.
  Property 'selectAll' does not exist on type 'IntrinsicAttributes & SelectProps<{ value: number; label: string; }>'. Did you mean 'onSelectAll'?ts(2322)`

**Comment by sanusart** [comment]
Should be fixed via v4.11.2
