### ISSUE TITLE
ISelectProps Interface contains initialize values instead of types.

### ISSUE THREAD

**Issue by nawazishalam** [sanusart/react-dropdown-select#26]
Current Interface

export interface ISelectProps {
  addPlaceholder: '';
  placeholder: 'Select...';
  values: [];
  options: [];
  multi: false;
  disabled: false;
  searchBy: 'label';
  sortBy: null;
  clearable: false;
  searchable: true;
  dropdownHandle: true;
  separator: false;
  keepOpen: undefined;
  noDataLabel: 'No data';
  createNewLabel: 'add {search}';
  disabledLabel: 'disabled';
  dropdownGap: 5;
  closeOnScroll: false;
  debounceDelay: 0;
  labelField: 'label';
  valueField: 'value';
  color: '#0074D9';
  keepSelectedInList: true;
  closeOnSelect: false;
  clearOnBlur: true;
  clearOnSelect: true;
  dropdownPosition: 'bottom';
  dropdownHeight: '300px';
  autoFocus: false;
  portal: null;
  create: false;
  direction: 'ltr';
  name: null;
  onChange: () => void;
  onDropdownOpen: () => void;
  onDropdownClose: () => void;
  onClearAll: () => void;
  onSelectAll: () => void;
  onCreateNew: () => void;
  searchFn: () => void;
  clearRenderer: ({ props: ISelectProps, state: IState, methods: IMethods }) => void;
  contentRenderer: ({ props: ISelectProps, state: IState, methods: IMethods }) => void;
  dropdownRenderer: ({ props: ISelectProps, state: IState, methods: IMethods }) => void;
  dropdownHandleRenderer: ({ props: ISelectProps, state: IState, methods: IMethods }) => void;
  inputRenderer: ({ props: ISelectProps, state: IState, methods: IMethods, inputRef: any }) => void;
  itemRenderer: ({
    item: number,
    itemIndex: number,
    props: ISelectProps,
    state: IState,
    methods: IMethods
  }) => void;
  loadingRenderer: ({ props: ISelectProps }) => void;
  noDataRenderer: ({ props: ISelectProps, state: IState, methods: IMethods }) => void;
  optionRenderer: ({ item, props: ISelectProps, state: IState, methods: IMethods }) => void;
  separatorRenderer: ({ props: ISelectProps, state: IState, methods: IMethods }) => void;
}

Error thrown in typescript
->Type '"Search..."' is not assignable to type '"Select..."'.
-> Type 'true' is not assignable to type 'false'.

**Comment by sanusart** [comment]
Thanks. Added in last version in attempt to add types. Will fix asap.
