### ISSUE TITLE
Property "values" is missing

### ISSUE THREAD

**Issue by jin-yee** [sanusart/react-dropdown-select#269]
I cannot get this working by referring to the basic, minimum working example from md file. The error shows up is

Property 'values' is missing in type '{ options: {}[]; onChange: { (...data: any[]): void; (message?: any, ...optionalParams: any[]): void; }; }' but required in type 'SelectProps<{}>'.

![image](https://user-images.githubusercontent.com/23400320/219296496-289aa309-546f-4e92-9973-e076da6b80d2.png)

I'm using React (18.0.28) with Typescript, the react-dropdown-select library is of version 4.9.3.

**Comment by sanusart** [comment]
Seem to be working fine on code sandbox
https://codesandbox.io/s/pensive-tom-xu21qj?file=/src/App.js
