### ISSUE TITLE
Error unique "key" prop

### ISSUE THREAD

**Issue by Xiryl** [sanusart/react-dropdown-select#27]
Hi, I try to make the same Dropdown as your baisc example, but I've got `Warning: Each child in a list should have a unique "key" prop.` error.

I use the same code of [this](https://github.com/sanusart/react-dropdown-select/blob/master/docs/src/examples/Basic.js) example and the same data taken from Options.js by your  [CodeSandbox](https://codesandbox.io/s/p54p8y1987?autoresize=1)

And in my HTML part i render by this code:

```
import { options } from './Options';
import Basic from './Basic';

<Basic
    options={options}
    title="example"
/>
```

And I've got this error:

```
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `Dropdown`. See https://fb.me/react-warning-keys for more information.
    in b (created by Dropdown)
    in Dropdown (created by b)
    in div (created by Context.Consumer)
    in ReactDropdownSelect (created by b)
    in div (created by b)
    in b (created by b)
    in b (at Basic.js:13)
    in Basic (at ConfigurationScreenContentPlaylist.js:77)
    in div (at ConfigurationScreenContentPlaylist.js:76)
    in div (at ConfigurationScreenContentPlaylist.js:75)
    in div (at ConfigurationScreenContentPlaylist.js:58)
    in div (at ConfigurationScreenContentPlaylist.js:56)
    in div (at ConfigurationScreenContentPlaylist.js:18)
    in aux (at ConfigurationScreenContentPlaylist.js:17)
    in ConfigurationScreenContentPlaylist (at ConfigurationScreenBase.js:24)
    in div (at ConfigurationScreenBase.js:41)
    in div (at ConfigurationScreenBase.js:34)
    in div (at ConfigurationScreenBase.js:33)
    in aux (at ConfigurationScreenBase.js:32)
    in ConfigurationScreenBase (created by Context.Consumer)
    in Route (at Layout.js:19)
    in aux (at Layout.js:13)
    in layout (at App.js:11)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.js:10)
    in App (at src/index.js:7)
```

How can I resolve?

**Comment by MiguelSOliveira** [comment]
I had that same problem. Changing the valueField prop to 'id' or another unique key solved it.

**Comment by Xiryl** [comment]
@MiguelSOliveira did you mean to change inside the data source? Because I have already a unique `id` value on my object

It is look like this:

```
export const options = [
  {
    id: 1,
    name: "Leanne Graham",
    username: "Bret",
    email: "Sincere@april.biz",
    address: {
      street: "Kulas Light",
      suite: "Apt. 556",
      city: "Gwenborough",
      zipcode: "92998-3874",
      geo: {
        lat: "-37.3159",
        lng: "81.1496"
      }
    },
    phone: "1-770-736-8031 x56442",
    website: "hildegard.org",
    company: {
      name: "Romaguera-Crona",
      catchPhrase: "Multi-layered client-server neural-net",
      bs: "harness real-time e-markets"
    }
  },
...
```

**Comment by aruljayaraj** [comment]
@MiguelSOliveira  can you explain how to resolve this issue? Where to change this one?

**Comment by pepies** [comment]
For me unique is not enought . Also `valueField` must be number.

**Comment by sanusart** [comment]
What do you mean value must be a number?

**Comment by pepies** [comment]
I have not investigated it in source.   
When I had in a valueField  property name that references to string key it was broken, than i changed it it `x.id` it worked so i moved on and left a comment.   
 But I guess it was not the problem. The real problem it that it is not covered by typescript and if property is renamed (ex. `x.project_code` to `x.code`) IDE wont refactor/rename occurance. And its sometimes hard to find out real problem.

**Comment by pepies** [comment]
Also becuase it not obvious that key is taken from valueField property.

**Comment by Xiryl** [comment]
If you pass an array of objects in the `options`, the prop `valueField` must be a unique identifier.
In my case, it also works with a timestamp in ISO format.

For example: 
```js
const options = [{...., createdAt: '...', name:'John Doe', ...}]
    <Select
      options={options}
      values={[]}
      placeholder={placeholder}
      valueField="createdAt"
      labelField="name"
      onChange={(values) => eventChange(values)}
    />
```

I hope this helps.
Enjoy your coding!
