### ISSUE TITLE
DefaultValue

### ISSUE THREAD

**Issue by TimoteoGambella** [sanusart/react-dropdown-select#277]
Can i put a default value when the component render?

**Comment by sanusart** [comment]
Just pass one or more options to the value prop as array:

values={[options[0]]}

**Comment by udarts** [comment]
@sanusart I want to know the same thing, I tried to add an array to the value, but it shows (54 of 5 selected), I have the contentRenderer.

I have the following array:
`[{"title": "Title1", "value": "Value1"},{"title": "Title2", "value": "Value2"}]`

**Comment by sanusart** [comment]
Can you reproduce in code sandbox?

**Comment by udarts** [comment]
@sanusart, hereby the codesandbox: https://codesandbox.io/p/sandbox/dropdown-test-z3fgqq?file=%2Fsrc%2FApp.js%3A85%2C25

As you can see the dropdown shows: 35 of 5 selected.

The const rooms holds all the values that the dropdown should show. The const dataFromDb is the data from the DB (hence the name). The dropdown should only show the value Room1 to be selected. But it should way more than it has.

**Comment by sanusart** [comment]
Hey, change the values prop to be:
values={[...dataFromDb]}

Not sure where the JSON.stringify idea came from.
