### ISSUE TITLE
emotion library is not imported correctly in components in lib folder

### ISSUE THREAD

**Issue by Abolfazl-ghodrati-k** [sanusart/react-dropdown-select#279]
instead of importing emotion correctly in those files its imported like this
`var _base = _interopRequireDefault(require('@emotion/styled/base'))`
while it should be 
`var _base = _interopRequireDefault(require('@emotion/styled-base'))`

**Comment by sanusart** [comment]
@Abolfazl-ghodrati-k do you know if this is related to a version of emotion?

**Comment by Abolfazl-ghodrati-k** [comment]
i hadn't installed emotion separately so i think its a conflict related to version

**Comment by sanusart** [comment]
I guess [this](https://github.com/emotion-js/emotion/pull/3029) is affecting. Will update emotion to latest

**Comment by sanusart** [comment]
Should be resolved in latest published v4.9.4 via #281
