### ISSUE TITLE
handleKeyDown override

### ISSUE THREAD

**Issue by sagedemdreisbusch** [sanusart/react-dropdown-select#28]
Hi there,
we are currently trying to use the react-dropdown-select in our project. Is it possible to override the handleKeyDown Function of index.js line 346?
We would really appreciate to handle it by ourselves because we want to use tabs, open the dropdown on input and so on.

Thank you and best wishes
Max

**Comment by sanusart** [comment]
@sagedemdreisbusch like this ☝️?

**Comment by sagedemdreisbusch** [comment]
Yes, that's it A lot of THANKS for the fast response and implementation :)

**Comment by sanusart** [comment]
Published v3.5.0
