### ISSUE TITLE
SSR is not supported

### ISSUE THREAD

**Issue by Rakesh-Harihar** [sanusart/react-dropdown-select#30]
not supported for **Server Side Rendering**

**Comment by sanusart** [comment]
Anything particular? Mismatches? Need more info.

**Comment by Rakesh-Harihar** [comment]
no.
when i try running my server js it breaks with the error "document is not defined". as document will not be available in ssr.

**Comment by santiagoGuti** [comment]
I had the same issue, I just bump to the version 3.6.3 and it works for me

**Comment by Valtech-India** [comment]
Thanks @santiagoGuti and @sanusart . I updated to v 3.6.3 and it works.

**Comment by Rakesh-Harihar** [comment]
Thanks @santiagoGuti and @sanusart. I updated to v 3.6.3 and it works.

**Comment by umervservices** [comment]
I am facing the same issue with 3.6.5 i tried react-no-ssr but no success

**Comment by sanusart** [comment]
Does 3.6.3 works with your setup?

**Comment by oktalk** [comment]
I'm using version 4.4.2 and my site is throwing errors when server side rendering. Did something change in the code base?

**Comment by sanusart** [comment]
Don't think something related changed. Will check.

**Comment by sanusart** [comment]
What error
