### ISSUE TITLE
When dropdown is open, clicking dropdown is not closing

### ISSUE THREAD

**Issue by musasahinkundakci** [sanusart/react-dropdown-select#303]
What i want to do is
Adding param like `closeOnInputClick`...

**Comment by musasahinkundakci** [comment]
I think it would be great bcz,
from mobile perspective it is not great...

**Comment by sanusart** [comment]
Hey. We already have 
```
closeOnSelect
```

**Comment by musasahinkundakci** [comment]
> Hey. We already have
> 
> ```
> closeOnSelect
> ```

No this is for option selection,
On input click, it should be closable...
Like mobile apps.
The select html input supports it.

**Comment by sanusart** [comment]
This is not comparable to html select.
Clicking outside should close it too. This is how most of selects work.

**Comment by sanusart** [comment]
Ok. Fair enough. But what about when in search mode?

**Comment by musasahinkundakci** [comment]
Search mode of course behaviour will change,
closeOnInput click will be disabled.
And in the doc it should be dictated.
What i think

**Comment by sanusart** [comment]
Make sense.
