### ISSUE TITLE
closeOnScroll not working when portal={document.body}

### ISSUE THREAD

**Issue by eran-or** [sanusart/react-dropdown-select#31]
closeOnScroll={true} not helping when I'm in modal and portal={document.body}
Is it need to work in this situation ?

**Comment by sanusart** [comment]
I wanna say it should but I never tested it in modal. Is modal is an iframe as well?
Any chance you can reproduce in in codesandbox or similar?

**Comment by sanusart** [comment]
Closing from lack of response
