### ISSUE TITLE
remove dropdown border

### ISSUE THREAD

**Issue by jacko06v** [sanusart/react-dropdown-select#310]
hi!
checked other user's code and docs, but didn't find anything
i changed the dropdown color with dropdownrenderer like that:

```
 dropdownRenderer={({ props, state, methods }) => {
          return (
            <div
              style={{
                backgroundColor: "#16102c",
                width: "10rem",
              }}
            >
              <input
                type="text"
                onChange={(e) => methods.setSearch(e.target.value)}
                value={state.search}
                placeholder="Search Network"
                style={{
                  width: "100%",
                  padding: "10px",
                  backgroundColor: "#16102c",
                  color: "white",
                  border: "none",
                  borderBottom: "1px solid #6853ad",
                  outline: "none",
                }}
              />
              <div>
                {props.options.map((item, index) => (
                  <div
                    key={index}
                    onClick={() => methods.addItem(item)}
                    style={{
                      backgroundColor: "#16102c",
                      padding: "10px",
                      margin: "5px",
                    }}
                    className="react-dropdown-select-item flex items-center"
                  >
                    <img
                      src={item.link_image}
                      alt={item.label}
                      className="w-6 h-6 mr-2"
                      style={{ borderRadius: "50%" }}
                    />
                    {item.label}
                  </div>
                ))}
              </div>
            </div>
          );
        }}
```

this is what i got:

<img width="181" alt="Screenshot 2024-02-16 alle 12 29 09" src="https://github.com/sanusart/react-dropdown-select/assets/76396947/a7cd1d25-d81d-406a-ad67-16fcc11280ef">

i would like to remove the white border and add a border radius, but i can't do that

**Comment by sanusart** [comment]
Just add style to the forst div element. Or check what css classes available

**Comment by jacko06v** [comment]
@sanusart alredy tried, doesn't change, if i try to add a border and make a border radius it add to the purple block:

first div:
```

<div
                  style={{
                    backgroundColor: "#16102c",
                    width: "100%",
                    border: "3px solid #6853ad",
                    borderRadius: "20px",
                    outline: "none",
                  }}
                >
```
result:

<img width="255" alt="Screenshot 2024-02-16 alle 19 36 41" src="https://github.com/sanusart/react-dropdown-select/assets/76396947/d4800470-aa5e-4643-adc3-76e121ef53ac">

it seems like a div inside a div, and i can edit just the child div

**Comment by sanusart** [comment]
Hey. You can edit the “react-dropdown-select-dropdown” class to style it.

**Comment by jacko06v** [comment]
thanks, react-dropdown-select-dropdown class worked:
<img width="251" alt="Screenshot 2024-02-17 alle 02 49 38" src="https://github.com/sanusart/react-dropdown-select/assets/76396947/7e7cff09-fb51-4b39-8d41-253e41b68fe5">
