### ISSUE TITLE
Changing state does not change selected value in dropdown

### ISSUE THREAD

**Issue by mfzha** [sanusart/react-dropdown-select#318]
```
const [something, setSomething] = useState({
  name: [],
  score: ""
});

const reset = () => {
  setSomething({
    name: [],
    score: ""
};

return(
  <>
    <button onClick={() => reset()}> Reset </button>
    <form onSubmit={doSomething}>
      <Select
        options={persons} // [{"name": "A", "id": 1}, ...]
        labelField="name"
        valueField="id"
        values={[...state.name]}
        onChange={(value) => {
          setSomething({...state, name: value.name})
        }}
      />
    </form>
  </>
);
```

Then calling `reset()` will reset `something` but the selected value will not revert to the default `Select...` placeholder.

This is after following https://github.com/sanusart/react-dropdown-select/blob/master/docs/src/examples/ExternalClear.js but making it functional.

**Comment by sanusart** [comment]
Your values and onChange does not look right.

Can you reproduce in code sandbox?

**Comment by mfzha** [comment]
@sanusart 
Here's the code sandbox [link](https://codesandbox.io/p/devbox/modest-swanson-h5njyz?workspaceId=e11d64c0-826c-4095-b664-4c6b0514bd61&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm07w1123000820684zoj8eik%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm07w112300032068w5x0rkom%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm07w112300052068vpfsqnqb%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm07w112300072068o3srpge5%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm07w112300032068w5x0rkom%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm07w112300022068t0pimpfa%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A7%252C%2522startColumn%2522%253A24%252C%2522endLineNumber%2522%253A7%252C%2522endColumn%2522%253A25%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cm07w112300032068w5x0rkom%2522%252C%2522activeTabId%2522%253A%2522cm07w112300022068t0pimpfa%2522%257D%252C%2522cm07w112300072068o3srpge5%2522%253A%257B%2522id%2522%253A%2522cm07w112300072068o3srpge5%2522%252C%2522activeTabId%2522%253A%2522cm07w80qu003t20680fxxobdd%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm07w112300062068m1o8u2p2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A5173%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522cm07w80qu003t20680fxxobdd%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522cm07w112300052068vpfsqnqb%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm07w112300042068f5k629am%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522cm07w112300052068vpfsqnqb%2522%252C%2522activeTabId%2522%253A%2522cm07w112300042068f5k629am%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by sanusart** [comment]
heres fixed fork:
https://codesandbox.io/p/devbox/vigilant-nash-wmqhnn?file=%2Fsrc%2FApp.tsx%3A27%2C27&workspaceId=b9b998fd-22ba-4002-9e32-f0bf90294b3a

**Comment by mfzha** [comment]
It's giving 404 Devbox not found, could you check permissions please?

**Comment by sanusart** [comment]
Sorry, [this one](https://codesandbox.io/p/devbox/vigilant-nash-wmqhnn?workspaceId=b9b998fd-22ba-4002-9e32-f0bf90294b3a) works

**Comment by mfzha** [comment]
The issue there becomes that the updated value of `player.name` is actually a copy of the entire player object of `A`, that is,
```
player.name = [{"id":"1","name":"A"}]
```
as can be verified by the line `App.jsx:52`
```
{JSON.stringify(player.name)}
```
whereas the intention is for the name to only be the name property of the player.

**Comment by sanusart** [comment]
This is the components API. You can filter whatever you need afterwards.

**Comment by mfzha** [comment]
The filtering has to be done after state is set though right? And the `Select` reflecting the state's `player.name` attribute should then be updated once the state has been set.

As it is now, the `player` state's `name` has to be the entire `person` object, to be filtered later -- there is no method to have it be just the `person.name`.

Please correct me if I'm saying something silly here by the way, I'm new to all of this so I might be thinking about it all the wrong way.

**Comment by sanusart** [comment]
Hey. No. Nothing silly here. Some similar components are working in the way
you describing. Native html select for example, works with flat string
arrays for example.
It is just this component designed in a way that it accepts array of object
and keeps selected values as array of objects. Just for the sake of
flexibility of working with data inside the components. For example to
build custom content from data inside the selected object.

**Comment by mfzha** [comment]
>  keeps selected values as array of objects.

I think that's the key here which I was missing. So if for instance I wanted the select to only be on names, I would either need to do as we discussed before (update state as the object and post-process it to only filter out the attribute I wanted), or pre-process `options` as an array of just names.

Is this something that would be immediately obvious to experienced devs? As it wasn't super obvious to me, I wonder if it might be helpful including this in the documentation?

In any case, thanks for the help! Feel free to close this issue out :)

**Comment by sanusart** [comment]
Not everyone the same no matter of experience IMHO.
I guess devs usually stop assuming and do debug at some point of life. I
might add to the docs. It is just bloated docs are also not always the best
option.
