### ISSUE TITLE
Error in Dropdown

### ISSUE THREAD

**Issue by sulaqo** [sanusart/react-dropdown-select#32]
Hi @sanusart 
I was trying using your component, but with a simple setup (from the code below ) I always getting an error about the "key" prop which is missing in Dropdown component
Am I made something wrong?

Each child in a list should have a unique "key" prop.
Check the render method of `Dropdown`.

```javascript
<Select
  options={[
    {
      id: "1654as6d54as",
      label: "label 1",
      name: "Tony"
    },
    {
      id: "2asdasdsadsas654",
      label: "label 2",
      name: "Tony's uncle"
    }
  ]}
  onChange={values => console.log(`%c > onChange ${values}`)}
/>;
```

**Comment by sanusart** [comment]
Hey. The only thing I see might cause it is that the each option should have "value" key (as this is what expected by default in addition to "label" key). 
Or you can add prop `valueField="name"` to the Select. 

I should probably mention it better in the docs.

**Comment by sulaqo** [comment]
Yeah that's correct !! It works. Thank you so much @sanusart
