### ISSUE TITLE
className prop is missing in types.d.ts define of ISelectProps, not inherited from elsehwere

### ISSUE THREAD

**Issue by stephen-dirtcreative** [sanusart/react-dropdown-select#33]
Creating a select in a typescript environment: (pseudo code)
```jsx
let options, // = options from somewhere
  onChange // = onChange from somewhere
<Select className={'class'} options={options} values={[]} onChange={onChange}/>
```
yields the error:
`Property 'className' does not exist on type 'IntrinsicAttributes & ISelectProps & { children?: ReactNode; }'.`

Observing types.d.ts in the npm package, there is no entry for className. Fixable by adding a line like:
`className?: string;` to `interface ISelectProps`

Workaround is to add monkey patch in code files that need className for Select:
```typescript
...
declare module 'react-dropdown-select' {
  interface ISelectProps {
    className?: string;
  }
}
...
```

**Comment by sanusart** [comment]
Fixed in 3.5.1 Thanks
