### ISSUE TITLE
onChange function is getting executed when component is mounted

### ISSUE THREAD

**Issue by s-shiva1995** [sanusart/react-dropdown-select#35]
Whenever a `Select` is mounted `onChange` function is getting executed, which should not happen as the component data is not getting changed initially.

**Comment by sanusart** [comment]
onChange is a callback prop. Why exactly is that a problem?

**Comment by s-shiva1995** [comment]
`onChange` should only be triggered whenever there is a change in value, but in this case you are calling this function whenever mount happens.
I am fetching data from api in `onChange` function but due to the execution of onChange on mounting, there is one extra api call always whenever componentDidMount is executed.

**Comment by sanusart** [comment]
OK. I understand your use case, please allow me to investigate why this line is present on `componentDidMount()`. There must be a reason.

**Comment by sanusart** [comment]
Thank you @s-shiva1995 
Published v3.6.0
