### ISSUE TITLE
Cycling dowpdowns with Tab wont allow to search them

### ISSUE THREAD

**Issue by linopereira** [sanusart/react-dropdown-select#38]
I have a couple of searchable dropdowns on a page, and when I use tab to cycle, they become focused, but the searchable input is not. I have to click to open and them make the search.
Is it possible to expose an onFocus callback?
Or if the dropdown  is focused and searchable... It should allow to search on key down?

**Comment by sanusart** [comment]
Published: v3.6.2

**Comment by linopereira** [comment]
This fixes the focus and open, but once focused, it won't cycle between different dropdowns. 
Only if I select a value.

**Comment by sanusart** [comment]
Hit escape to loose focus of open one and continue with tabs.
