### ISSUE TITLE
clicking dropdown handle causes dropdown to open and immediately close

### ISSUE THREAD

**Issue by LaurenMae** [sanusart/react-dropdown-select#39]
clicking on the dropdown handle and not the select element causes the dropdown to open and immediately close - almost like a hover effect.  I would expect this action to behave in the same way as clicking on the select to open the dropdown

**Comment by linopereira** [comment]
[NewProject.pdf](https://github.com/sanusart/react-dropdown-select/files/3647681/NewProject.pdf)

I have a similar issue... please check the attached pdf.
Everytime I click on the dropdown it immediately closes.
If I remove the position absolute from the overlay over the table, it works fine.
(I need to block interation with table until the users selected a value, but putting an overlay between the portal and actual dropdown have the described behaviour)

**Comment by sanusart** [comment]
Published v3.6.3

**Comment by CeciliaCaroline** [comment]
I still  have this issue even if I am using v3.6.3
