### ISSUE TITLE
Option for closing dropdown by clicking dropdown content

### ISSUE THREAD

**Issue by user010110** [sanusart/react-dropdown-select#40]
There's no option to close dropdown by clicking dropdown content (selected value) in dropdown 'header'. You can close dropdown by clicking option item or outside the component. Is there any workaround?

**Comment by sanusart** [comment]
Is that what you need?
https://sanusart.github.io/react-dropdown-select/prop/option-renderer

**Comment by user010110** [comment]
No, unfortunately it's not. What I had in mind is clicking again 'Select' when dropdown is opened

**Comment by sanusart** [comment]
Yes you can achieve that with this custom renderer. I am not sure clicking the pill should act as drop-down trigger.

**Comment by user010110** [comment]
Yeah I should've probably mentioned I am using your component as single-value select, so there're no pills, just text.

**Comment by sanusart** [comment]
Yep I think you right.  It should do that when non multi. I'll look into that.

**Comment by sanusart** [comment]
Now that I am playing with the demo I am not sure it should do that even when not in multi mode. Can you please expand on your use case? Maybe I am missing something.

**Comment by user010110** [comment]
Here: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select. I am referring to the HTML's 'select' element

**Comment by sanusart** [comment]
Bit this is not an html select. Underneath, if used in a form it only expose input of type "text". 

While I understand your point, I am still not convinced it should behave as per your description being what it is as apposed to native select. 

Moreover, some (Chrome on Android for example) implement native select in such way, where options are covering the select head entirely, so user has no select header to interact with at all.
