### ISSUE TITLE
Rerendering getting out of hands

### ISSUE THREAD

**Issue by user010110** [sanusart/react-dropdown-select#41]
![image](https://user-images.githubusercontent.com/55839043/65688290-25b12680-e06b-11e9-8abd-6b5f2e1cc341.png)
There's uncontrolled state changing spam happening, please see the attachment above.
I believe setting a value to 'dropdownPosition' prop should preserve checking for boundaries

**Comment by sanusart** [comment]
Can you explain more on what you call uncontrolled? It is not useful as is. What you show is boundaries calculations. Yes it can be improved. If you have any suggestions please share.
