### ISSUE TITLE
Span element is not blockable

### ISSUE THREAD

**Issue by LaurenMae** [sanusart/react-dropdown-select#42]
The span element used in the dropdown content is not able to be restricted to its parents size.  My use case is being able to set the dropdown to a particular size and any options with labels too long having ellipsis applied in the content.

The below screen shot shows a name that is too long for the parent size, the span overflows the parent and the text is unreadable.

![Screenshot 2019-10-01 at 15 46 03 (2)](https://user-images.githubusercontent.com/12128687/65973966-11eb3300-e464-11e9-9b1b-f4e9697c19c5.png)

The below screen shot shows desired behaviour which can be achieved by swapping the span element for a div element
![Screenshot 2019-10-01 at 15 44 50](https://user-images.githubusercontent.com/12128687/65974092-40690e00-e464-11e9-8f85-292712d73145.png)

**Comment by sanusart** [comment]
Doesn't styling it to block not solving your issue?

**Comment by LaurenMae** [comment]
Unfortunately not, I can set the display to block or inline block which somewhat fixes the problem. When the drop down is open the content continues to shift and the word wrap is no longer functional as the spans content is still greater than its parent: 
![Screenshot 2019-10-01 at 16 11 53](https://user-images.githubusercontent.com/12128687/65975226-35af7880-e466-11e9-83dd-fd3165972725.png)

**Comment by sanusart** [comment]
Got it. Will check it out.

**Comment by LaurenMae** [comment]
Is there any progress on this issue? Thanks

**Comment by sanusart** [comment]
https://codesandbox.io/s/react-dropdown-select-so9nz

**Comment by LaurenMae** [comment]
That looks great! 👍 Thank you
