### ISSUE TITLE
Typescript Error when using searchFn

### ISSUE THREAD

**Issue by sagedemdreisbusch** [sanusart/react-dropdown-select#43]
Hi Sasha,

we are using react-dropdown-select component in our project. It really works great but we have one issue with typescript.

When giving a own searchFn to the component, typescript brings up an error because the function is typed as () => void. May it be possible to chenge the type to something like 'searchFn?: ({ props, state, methods }: IRenderer) => object[];' ?

A lot of thanks and best wishes
Max

**Comment by sanusart** [comment]
Published version: v3.6.4, thank you!

**Comment by sagedemdreisbusch** [comment]
Great, a lot of thanks for fixing and acting so quickly :)
