### ISSUE TITLE
Tab Handling

### ISSUE THREAD

**Issue by sagedemdreisbusch** [sanusart/react-dropdown-select#46]
Hi Sasha,
currently we are having some troubles with tab-handling. During reasearch I found out, that there is no possibility to give the component an own tabIndex. Might it be possible to give tabIndex as a prop to the main component for setting it to the high div and also to the input component? (we have an own content renderer but currently using the default input)

If you wish us to contribute, just tell me.

Thanks a lot and best wishes
Max

**Comment by sanusart** [comment]
Hey, maybe I am missing something, but there is tabindex on the component,
also there is "additionalProps" prop available to pass more props to a
component.

**Comment by sagedemdreisbusch** [comment]
You are right, there is a tabindex, but it does not override anything, does it? If I give the prop tabindex={-1} to any of the two, nothing happens on DOM

**Comment by sanusart** [comment]
Have you tried:

additionalProps={ { tabIndex: -1 } }

**Comment by sagedemdreisbusch** [comment]
Yeah I did, then the select is not entered any more even if I put tabIndex: 0 in the Input component. The problem is, that the tab handling is working fine on Pressing 'Tab' but normally you can go to previous fields with Shift+'Tab' but this is not working. Have you got any suggestions for that?

**Comment by sanusart** [comment]
I guess tabs listeners can be added along with the arrows here: https://github.com/sanusart/react-dropdown-select/blob/98ad37d88675b8f8345c5cbee19b77d2cde7d332/src/index.js#L358 But I suspect it wont be as easy as just to add them. 
Will look into that as this is probably proper behaviour. If you have any suggestions, please share.

Haven't #28 worked out?

**Comment by sagedemdreisbusch** [comment]
Yeah #28 worked great for dropdown handling and also for the normal Tab, but shift-tab is not working either

**Comment by sanusart** [comment]
So latest latest should have the tabs

**Comment by sagedemdreisbusch** [comment]
That's great, a lot of thanks

**Comment by lopesc** [comment]
This doesn't seems to work when using customItemRenderer - is there a recommended way to hook into the key navigation.

**Comment by sanusart** [comment]
handleKeyDownFn

Should do it I think, last in the table here
https://sanusart.github.io/react-dropdown-select/api

**Comment by lopesc** [comment]
Hmmm ok, I'll take a look. My understanding is that the internal `handleKeyDown` function performs a lot of information related to updating the stat of the dropdown, selected items, etc... I don't really want to override any of that - just need a way to hook into what item is currently selected in the results.

**Comment by sanusart** [comment]
Oh I think you can get it via `state.values`, it looks exposed in [itemRenderer](https://sanusart.github.io/react-dropdown-select/prop/item-renderer) param. Will that work?

**Comment by lopesc** [comment]
Will take a look, thanks for the advice

**Comment by quockhanhle93** [comment]
> Yeah #28 worked great for dropdown handling and also for the normal Tab, but shift-tab is not working either
> Am trying to fix it and giving you feedback

Hi @sagedemdreisbusch , have "Shift + Tab" worked on latest version? I try to download the latest version, it works with Tab by moving to a next element, but "Shift + Tab" does not go back to the previous element. Any suggestion, thanks?

**Comment by quockhanhle93** [comment]
@sanusart May you give me some suggestions on "Shift + tab" issue. Thanks a lot.

**Comment by sanusart** [comment]
@quockhanhle93  It works on the main demo. https://sanusart.github.io/react-dropdown-select/
Are you overriding something?

**Comment by quockhanhle93** [comment]
@sanusart Sorry for not describing my issue carefully. 

My issue is to move from 1 dropdown to another dropdown. It works well with Tab to move forward to next element. For Shift tab, it is expected to move back to the previous dropdown (or another element), but it is not. Please help me see below image, for using Shift + tab, it is expected to jump back to github icon.

![image](https://user-images.githubusercontent.com/15141480/80118260-ae4b6300-8577-11ea-898e-dceb789deae5.png)

Anyway, I overrides `handleKeyDownFn` to only use arrowUp and arrowDown to moving among options.

```
const handleKeyDownFn = ({ event, state, props, methods, setState }) => {
    const { cursor } = state
    const escape = event.key === 'Escape'
    const enter = event.key === 'Enter'
    const arrowUp = event.key === 'ArrowUp'
    const arrowDown = event.key === 'ArrowDown'
    const backspace = event.key === 'Backspace'
    const tab = event.key === 'Tab' && !event.shiftKey
    const shiftTab = event.shiftKey && event.key === 'Tab'

    if (enter && cursor === null) {
      setStatus({ shown: true })
      return setState({
        cursor: 0
      })
    }

    if (arrowUp || arrowDown || shiftTab || tab) {
      event.preventDefault();
    }

    if (enter || tab || shiftTab) {
      const currentItem = methods.searchResults()[cursor]
      if (currentItem && !currentItem.disabled) {
        if (props.create && valueExistInSelected(state.search, state.values, props)) {
          return null
        }
        methods.addItem(currentItem)
      }
    }    

    if (arrowDown && methods.searchResults().length === cursor) {
      setState({
        cursor: 0
      })
    }

    if (arrowUp && cursor === 0) {
      setState({
        cursor: methods.searchResults().length - 1
      })
    }

    if (backspace && props.multi && props.backspaceDelete && getInputSize() === 0) {
      setState({
        values: state.values.slice(0, -1)
      })
    }
  }
```

**Comment by sanusart** [comment]
Yes, I see how it braking the chain of shift+tab navigation. 
Probably related to what we discussed in #88 need to find fine line to handle proper keyboard navigation also outside the component.

**Comment by quockhanhle93** [comment]
Yes, you are right. It is somehow related to what we discussed in #88. Thanks @sanusart
