### ISSUE TITLE
Using react-dropdown-select with Typescript

### ISSUE THREAD

**Issue by Lukortech** [sanusart/react-dropdown-select#49]
Hello, I've found out that creating my own component to represent ListItem in TS is a bit difficult.

![Zrzut ekranu z 2019-11-13 12-46-55](https://user-images.githubusercontent.com/26508593/68761157-c8216b00-0613-11ea-834b-d5ad5eba1adf.png)

Methods don't accept any parameters in types, so getting it to work later on requires either //@ts-ignores or just always checking at the beginning if(param!==undefined). 

![Zrzut ekranu z 2019-11-13 12-48-38](https://user-images.githubusercontent.com/26508593/68761263-04ed6200-0614-11ea-9c13-263c261971c5.png)

Maybe I'm doing something wrong, in which case, please let me know.

**Comment by sanusart** [comment]
Hey what version? @lopesc was very kind of adding more proper typings in a past few days. Can you check if 3.6.7 solving it for you?

**Comment by Lukortech** [comment]
Hey @sanusart ! 
It seems I've been trying to do it in older version. I've seen that in latest it's easier since types are there. 
Thanks @lopesc !

Closing as updating solved the issue.

**Comment by lopesc** [comment]
No problem!
