### ISSUE TITLE
Dropdown items double highlight

### ISSUE THREAD

**Issue by yairEO** [sanusart/react-dropdown-select#5]
It seems weird to me that two items can be highlighted at the same time from the dropdown list. one with the keyboard and another one with the mouse, and each has a slightly different style. The keyboard one seems to have a "bold" text.

Is this a feature or a bug?

**Comment by sanusart** [comment]
I wanna say it is feature, but I smell design bug over there. Need to check.

**Comment by sanusart** [comment]
Should be without bold font after v2.1.2
