### ISSUE TITLE
Clear on Select - Searchable

### ISSUE THREAD

**Issue by codeBelt** [sanusart/react-dropdown-select#54]
Maybe I am not clear on how `clearOnSelect` works but I am would like the users to select one item from the select menu which calls the `onChange` method but not remember the items so the user can search for a new item right away. I will be showing the selected results in another component.

```
<Select
    searchable={true}
    clearOnSelect={true}
    clearOnBlur={true}
    options={items}
    onChange={values => console.log(values)}
/>
```

https://stackblitz.com/edit/react-mzsu7r

**Comment by sanusart** [comment]
As per props list in the readme and docs, clearOnSelect clears search value from input.

**Comment by milily** [comment]
`clearOnSelect` doesn't answers the question. I need it too to clear selected value from component and search too, to have again the placeholder

**Comment by sanusart** [comment]
You can set values to `[{}]` using `onChange()` after you have your
selected value(s). Will that work for you?
