### ISSUE TITLE
Required Flag missing

### ISSUE THREAD

**Issue by sagedemdreisbusch** [sanusart/react-dropdown-select#59]
Hi Sasha,
we have an issue with test automation when the dropdown is a required field. Is it possible to add the required flag to the html of the component?

Thanks a lot and best wishes
Max

**Comment by sanusart** [comment]
Hey, does passing it to `additionalProps` as object helps?
E.g. `additionalProps={{ required: true }}`

**Comment by sanusart** [comment]
@sagedemdreisbusch 
Checkout this build from [pull request 60](https://github.com/sanusart/react-dropdown-select/pull/60). 

https://deploy-preview-60--react-dropdown-select.netlify.com/examples#Form-with-validation-(using-react-live) Is that solves the issue?

**Comment by sagedemdreisbusch** [comment]
Hi Sasha, thank you very much for the really fast solution.
Seems to be the right one.

Best wishes Max
