### ISSUE TITLE
styling with css-modules?

### ISSUE THREAD

**Issue by megantaylor** [sanusart/react-dropdown-select#6]
any thoughts as to how to style the component using css-modules instead of CSS-in-JS? i kindof got around this using global styles, but that also feels pretty gross. would appreciate any guidance.

**Comment by sanusart** [comment]
Not sure if that is what you currently have, but if not, you can wrap it with your own DOM node with class and style it using built-in classes:

```sass
.select-wrapper {
  :global {
    .react-dropdown-select-item-active { // this is class used for the dropdown item
      font-weight: 600;
    }
  }
}
```
