### ISSUE TITLE
Dropdown-Input is selectable when disabled and using tab-key.

### ISSUE THREAD

**Issue by gandalf92** [sanusart/react-dropdown-select#62]
Expected behavior:
The input should not be selectable when it is disabled using the tab-key.

Current Behavior:
The input is selectable via tab-key and the dropdown is visible.

Fix:
Set tabindex to -1 on outer container when disabled and don't render options-list.

**Comment by sanusart** [comment]
Thank you @gandalf92 published v3.10.0
