### ISSUE TITLE
Select fields can't be blured by tab

### ISSUE THREAD

**Issue by gandalf92** [sanusart/react-dropdown-select#64]
Problem:
When deaktivating tab-behavior inside of the handleKeyPress-callback by something writing like this:

```js
if (key === 'tab') {
  methods.dropDown('close');
  return true;
}
```

the select can't be blurred.

Solution:

Prevent event-bubbleing and set tabindex of the input in index.js to -1.

**Comment by sanusart** [comment]
Thank you @gandalf92 
Published v3.11.0
