### ISSUE TITLE
Incompatible with SSR

### ISSUE THREAD

**Issue by ramraphael** [sanusart/react-dropdown-select#66]
The core component seems to be adding event listeners on the window object without checking the environment it's being executing on, which causes errors in Node during SSR.

**Comment by sanusart** [comment]
It would be really helpful to see the errors, the snippet used that triggers error and in general more about the environment error is happening. 
In order to try to reproduce as close as possible because I do not load it any ssr app.

**Comment by sanusart** [comment]
This is regression started after 3.6.3
Something changed in emotion used for styling

**Comment by sanusart** [comment]
Fix version: 4.0.0
