### ISSUE TITLE
Not able to select 6th option onwards v2.2.3

### ISSUE THREAD

**Issue by SashyCashy** [sanusart/react-dropdown-select#7]
```
options =[0: {id: "10", value: "10", label: "Channel 1 10", type: "channels", valid_routing_id: 50, …}
1: {id: "1", value: "1", label: "Channel 2 1", type: "channels", valid_routing_id: 41, …}
2: {id: "2", value: "2", label: "Channel 3 2", type: "channels", valid_routing_id: 42, …}
3: {id: "3", value: "3", label: "Channel 4 3", type: "channels", valid_routing_id: 43, …}
4: {id: "4", value: "4", label: "Channel 5 4", type: "channels", valid_routing_id: 44, …}
5: {id: "5", value: "5", label: "Channel 6 5", type: "channels", valid_routing_id: 45, …}
6: {id: "6", value: "6", label: "Channel 7 6", type: "channels", valid_routing_id: 46, …}
7: {id: "7", value: "7", label: "Channel 8 7", type: "channels", valid_routing_id: 47, …}
8: {id: "8", value: "8", label: "Channel 9 8", type: "channels", valid_routing_id: 48, …}
9: {id: "9", value: "9", label: "Channel 10 9", type: "channels", valid_routing_id: 49, …}
];
```

--------------------------------------------------------------------------
/* This is where I am invoking the object, 6th option onwards I cannot select. I had to degrade my npm module to 2.0.0 from 2.2.3 and it is working fine */
```
<MultiSelect
            values={preSelectedValues}
             options={options}
            searchable={false}
            onChange={(arr) => optionClicked(arr)}
            onDropdownClose={() => this.closeDropDown()}
            onDropdownOpen={() => this.openDropDown()}/>
```

**Comment by sanusart** [comment]
Hi, I created a quick codesandbox for you here https://codesandbox.io/s/8nnqkm14l0 
Try to reproduce it there as close as possible to your code.

**Comment by SashyCashy** [comment]
Thank you! I have tried to recreate the issue for you. You can try clicking on some of the options **below** for 2nd or 3rd MultiSelect.

**Comment by sanusart** [comment]
@SashyCashy I see no link

**Comment by SashyCashy** [comment]
https://codesandbox.io/s/q3rm21pjoj

**Comment by sanusart** [comment]
It seems like it works as expected. Can you be more specific regarding
browser you use? Maybe it's specific browser version?

**Comment by SashyCashy** [comment]
I am using Chromium v55. and basically just doing https://codesandbox.io/s/q3rm21pjoj this

**Comment by sanusart** [comment]
Hmm. v55 sounds pretty old, Isn't it v70+ this days? Not sure that old browser version should be supported.

**Comment by SashyCashy** [comment]
@sanusart  I think we can close this issue as reverting back to the older version has fixed my issue.
