### ISSUE TITLE
Have onRequestClose callback for animation

### ISSUE THREAD

**Issue by Krispy3000** [sanusart/react-dropdown-select#78]
Hello, I wanted to add some animations to react-dropdown-select on open and close, and while I could hack something together using the methods it'd be better if the callback structure supported this. Currently there is just a `onDropdownClose` and `onDropdownOpen` callback. It's easy enough to have an animation trigger on the `onDropdownOpen` callback since the element is created, I can start it at an "off" position then animate to "enter", but this isn't possible with `onDropdownClose` where the element is immediately removed.

The solution I suggest is the one used by react-modal: https://reactcommunity.org/react-modal/

Here there is also a `onRequestClose` callback for when the user wants to handle closing the item manually. This way I could run my own animation (using react-spring) and then once the animation is done call the dropdown close method.

**Comment by sanusart** [comment]
@Krispy3000 
Do you think specifying timeout to eliminate the need to call dropdown close method is overkill?
Anyway will see how muck more complication it adds.

**Comment by Krispy3000** [comment]
For my case a timeout wouldn't be sufficient because I'll be using fancy spring animations which don't have a definite end. However, I think react-modal handles that more common, simpler case too: https://github.com/reactjs/react-modal/blob/master/docs/styles/transitions.md

**Comment by sanusart** [comment]
So basically, if user sets `onRequestClose` - select should fire callback and block the dropdown from closing, as opposed to `onDropdownClose` which is firing after the actual close. Correct?

**Comment by Krispy3000** [comment]
Correct. Basically I want to have control over opening and closing the dropdown from the parent component so I can program custom interactions, in this case a spring animation. This way I can take advantage of all the edge cases your component already covers for closing the dropdown and execute my own logic when that request comes back.

**Comment by sanusart** [comment]
Got it. So I will also probably add some close timeout prop in addition for simplier use cases with pure css animations. Thanks!

**Comment by sanusart** [comment]
@Krispy3000 
Can you check if it is working for you like in pr #80 
You can istall the package build by code sandbox https://ci.codesandbox.io/status/sanusart/react-dropdown-select/pr/80/builds/12682

**Comment by Krispy3000** [comment]
It works and you can take a look at my code example: https://codesandbox.io/s/ancient-tree-fke4p?fontsize=14&hidenavigation=1&theme=dark

Note that the first open animation doesn't work for some reason, but the subsequent ones do. I haven't figured out where the problem lies yet.

Also, I accidentally tried using methods.dropDown to close the dropdown on request and it caused an infinite loop. Might be good to warn against that.

**Comment by sanusart** [comment]
So I used to test with simple CSS. My example is at the bottom of the page https://deploy-preview-80--react-dropdown-select.netlify.com/examples/

Have you solved the first open animation, shall we merge or wait a bit to see that it is not and issue.
Noted the loop when calling from `methods.dropDown` will see how to block this or document. Thanks!

**Comment by Krispy3000** [comment]
I don't think I can isolate the animation issue for a few days and I don't think you should hold up merging for that. 

However, I did notice the simple CSS version had an issue where about 50% of the time the dropdown flashed when being closed: https://www.dropbox.com/s/rsr1gaqfxugy6zy/Screen%20Recording%202020-03-03%20at%2011.25.21%20AM.mov?dl=0

I suspect the fix is to add `animation-fill-mode: forwards` so that if the there is a 1 frame difference between the animation finishing and the dropdown closing that it preserves its hidden styles.

**Comment by sanusart** [comment]
Yes. That because I "cheated" the delay with timeout :smile: 
I'll test it a little bit more manually and then merge. 

Thanks for the input!

**Comment by sanusart** [comment]
Released v4.2.0
Thank you!
