### ISSUE TITLE
CustomContentAndDropdown returning title is undefined error

### ISSUE THREAD

**Issue by bigBxr** [sanusart/react-dropdown-select#85]
Hi,
I am new to React, and an intermediate in Javascript. I forked CustomContentAndDropdown.js and Heading.js for a project I'm working on. But when I ran them I got an error message "title is undefined" for Heading.js.
I made a few changes to the code and removed Heading.js from CustomContentAndDropdown.js since I do not heed a header. But every time I type in a special character like a backslash or square brackets in the search field, my app crashes.

Q1- I saw there were a few special character formatting code in Heading under anchorify. So I'm now trying to use Heaing again but still having the same issue "title is undefined". How do I make the search field not crash my app when inputing special characters?

Q2- How do I use this component in my other component? Do I import it as "CustomContentAndDropdown" then add "labelField" and "valueField" or do I add those inside "CustomContentAndDropdown.js" component.

Q3- How do I get the "labelField" and "valueField"to display the city? I made them ="address.city" but that returned and empty label.

Thank you very much

**Comment by sanusart** [comment]
Hey, 

Q1 - you can see it is not crushing in the demos and examples.
Q2 - here is simplified example https://codesandbox.io/s/react-dropdown-select-z4d6d
Q3 - see simple example of nested datasource here https://codesandbox.io/s/react-dropdown-select-cok1i

**Comment by bigBxr** [comment]
Hi thanks for the prompt response,
Q1- When I try "[" or "\" in the CustomContentAndDropdown demo it crashes.

Q3- When I use "address.city" in the CustomContentAndDropdown sample code it does not work.

Thanks!

**Comment by sanusart** [comment]
Q1, is just an example. You need to modify the search regex, it is very basic, just for example https://github.com/sanusart/react-dropdown-select/blob/master/docs/src/examples/CustomContentAndDropdown.js#L20

Q3 - it is hard to tell without seeing your setup. Can you reproduce in code sandbox?

**Comment by bigBxr** [comment]
Thank you
