### ISSUE TITLE
Keyboard navigation with custom itemRenderer

### ISSUE THREAD

**Issue by Kakedragge** [sanusart/react-dropdown-select#89]
Hi,

I am using the react-dropdown-select with a custom itemRenderer. 
While navigating through the options of the dropdown i noticed there where no focus styling on my items, and I was not able to find a way to fix this myself. I also tested it on your itemRenderer  example and it also had the same issue. 

Do you know of any ways to work around this? 
Thanks, 
Simon.

**Comment by sanusart** [comment]
Hi, this examples are extremely simple.
You can check if current item is the one being active via navigation by matching `state.cursor === itemIndex` and style according to that. 

Example: https://codesandbox.io/s/itemrenderer-iixn7
