### ISSUE TITLE
Access internal props onDropdownClose

### ISSUE THREAD

**Issue by andybeli** [sanusart/react-dropdown-select#91]
Hi, 

First off all amazing dropdown!

**Scenario:**
I've customised the component to be able to have a limit on the amount of multiple options a user can selected. Might be a nice feature to add. The user selects two options, the dropdown list disappears and I hide the dropdownHandler arrow.

**The problem:**
I need to check onDropdownClose or onBlur `state.values.length` to handle error message but this methods doesn't have access to the internal properties.

What would be a good alternative? Couldn't find an alternative in the docs.

**Comment by sanusart** [comment]
Hey, we recently added `onDropdownCloseRequest` callback prop.
It has access to methods, props, state and special function close().
It stops the drop-down from close. When you done you need to call the
close() to close the drop-down.

This should do it I think.

**Comment by andybeli** [comment]
That works perfectly thanks!
