### ISSUE TITLE
Same searchable name , but different ID

### ISSUE THREAD

**Issue by michaelkoswara** [sanusart/react-dropdown-select#97]
Hi there, 

Thanks for fixing the keepDropdownOpen bug the other day.

I have another question and i'm not sure if this is a bug, or intended, or if there is another way around it:

I have a json array of person profile. 
There is a chance that there could be two people with the same names (ie. 2 people named John Doe ).

At the moment, the component is warning me about unique keys.
And also when i select "John Doe" from the dropdown, both of them get selected.

I know this is because i have set **valueField=name**

But I need this because the searchable inputbox needs to search by name, not id. 

So how can i get around this ?

**Comment by sanusart** [comment]
Hey @michaelkoswara 
You don't have to define valueField just to be able to search by it. 
You can use `searchBy` to tell it to search by something else. Will that work?

It sound reasonable to me that values should be unique. Unless you can prove me wrong :)

**Comment by michaelkoswara** [comment]
@sanusart 
Ah I missed that `searchBy` prop in your api list. 

So it works now with a combination of :
searchBy="name"
valueField="id"

If i don't include the valueField prop, it actually selects all the items when i select one.
Does this sound ok to you ? Or am i meant to do it a different way ?

**Comment by sanusart** [comment]
Is this similar to your use case: https://codesandbox.io/s/react-dropdown-select-jy184

**Comment by michaelkoswara** [comment]
@sanusart 
Yep, pretty much. There are lots more property per "person" , but it's the same use case yes.
And i've done it your way (include both searchBy=name , valueField=id) , and it's working. 

Thanks !
