### ISSUE TITLE
Do I have to guess what the layout of the values array looks like? There is no example.

### ISSUE THREAD

**Issue by rodrigofbm** [sanusart/react-dropdown-select#99]
Do I have to guess what the layout of the values array looks like? There is no example...

**Comment by sanusart** [comment]
Yes. You can try to guess. If you not succeeded, please check how examples work. You don't have to have special structure. You can specify what to use as labelField and valueField via props.

**Comment by rodrigofbm** [comment]
Thanks this man for a better example:
[Link](https://codesandbox.io/s/react-dropdown-select-jy184?file=/src/index.js:453-514)
